"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { ArrowLeft, ChevronLeft, ChevronRight, Download, Eye, FileText, Grid2X2, List, LoaderCircle, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import type { Conversation, ConversationSummary, StorageFile, StoredAttachment } from "@/lib/types";
import { useModalFocus } from "@/lib/use-modal-focus";
import { SelectMenu } from "./select-menu";

type AuditUser={id:string;username:string;displayName:string};
type PageResult<T>={items:T[];total:number;page:number;pageSize:number;pageCount:number};
type FilePage=Omit<PageResult<StorageFile>,"items">&{files:StorageFile[];usedBytes:number;quotaBytes:number;sort:string};
const bytes=(value:number)=>value>=1024**3?`${(value/1024**3).toFixed(2)} GB`:value>=1024**2?`${(value/1024**2).toFixed(1)} MB`:`${Math.max(.1,value/1024).toFixed(1)} KB`;
const resource=(userId:string,id:string,inline=false,thumbnail=false)=>`/api/users/${encodeURIComponent(userId)}/audit?download=media-file&uploadId=${encodeURIComponent(id)}${inline?"&inline=1":""}${thumbnail?"&variant=thumbnail":""}`;
const mappedResource=(userId:string,value:unknown,inline=false)=>{const source=typeof value==="string"?value:"";const match=/^\/api\/uploads\/([a-zA-Z0-9_-]+)/.exec(source);return match?resource(userId,match[1],inline):source;};

function DialogFrame({title,subtitle,ko,onBack,onClose,children,footer,className=""}:{title:string;subtitle:string;ko:boolean;onBack?:()=>void;onClose:()=>void;children:React.ReactNode;footer?:React.ReactNode;className?:string}){
  const ref=useModalFocus(onClose);
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer managed-user-layer" role="dialog" aria-modal="true" aria-label={title}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><section className={`harness-dialog audit-browser-dialog ${className}`}><header><div className="audit-dialog-title">{onBack&&<button onClick={onBack} aria-label={ko?"뒤로":"Back"}><ArrowLeft size={18}/></button>}<div><h2>{title}</h2><p>{subtitle}</p></div></div><button onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>{children}{footer&&<footer>{footer}</footer>}</section></div>,document.body);
}

function Pager({page,pageCount,total,ko,onPage}:{page:number;pageCount:number;total:number;ko:boolean;onPage:(page:number)=>void}){
  return <nav className="audit-pager" aria-label={ko?"페이지 이동":"Pagination"}><button disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={16}/></button><span>{page} / {pageCount}<small>{ko?`총 ${total}개`:`${total} total`}</small></span><button disabled={page>=pageCount} onClick={()=>onPage(page+1)}><ChevronRight size={16}/></button></nav>;
}

function AuditAttachment({userId,file}:{userId:string;file:StoredAttachment}){
  return <a className="audit-chat-attachment" href={resource(userId,file.id)} target="_blank" rel="noreferrer">{file.mimeType.startsWith("image/")?<img src={resource(userId,file.id,true,true)} alt={file.name}/>:<FileText size={24}/>}<span><strong>{file.name}</strong><small>{bytes(file.size)}</small></span></a>;
}

function ConversationViewDialog({user,conversationId,ko,onBack,onClose}:{user:AuditUser;conversationId:string;ko:boolean;onBack:()=>void;onClose:()=>void}){
  const[data,setData]=useState<Conversation>();const[branchId,setBranchId]=useState("");const[notice,setNotice]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch(`/api/users/${encodeURIComponent(user.id)}/audit?view=conversation&conversationId=${encodeURIComponent(conversationId)}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);const conversation=body.conversation as Conversation;setData(conversation);setBranchId(conversation.activeBranchId||conversation.branches[0]?.id||"");}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load conversation.");});return()=>controller.abort();},[conversationId,user.id]);
  const branch=data?.branches.find(item=>item.id===branchId)||data?.branches[0];
  return <DialogFrame title={data?.title||(ko?"채팅 불러오는 중":"Loading conversation")} subtitle={`@${user.username}${data?` · ${data.branches.length} ${ko?"개 분기":"branches"}`:""}`} ko={ko} onBack={onBack} onClose={onClose} className="conversation-review-dialog"><div className="audit-review-toolbar">{data&&<SelectMenu label={ko?"분기":"Branch"} value={branch?.id||""} options={data.branches.map(item=>({value:item.id,label:item.name}))} onChange={setBranchId}/>}<a className="subtle-action" href={`/api/users/${encodeURIComponent(user.id)}/audit?download=conversation&conversationId=${encodeURIComponent(conversationId)}`}><Download size={14}/>{ko?"압축 다운로드":"Download ZIP"}</a></div>{notice&&<p className="settings-notice">{notice}</p>}{!data&&!notice&&<div className="audit-loading"><LoaderCircle className="spin" size={20}/></div>}<div className="audit-conversation-view">{branch?.messages.map(message=><article key={message.id} className={message.role}><header><strong>{message.role==="user"?(ko?"사용자":"User"):(ko?"어시스턴트":"Assistant")}</strong><time>{new Date(message.createdAt).toLocaleString(ko?"ko-KR":"en-US")}</time></header>{message.attachments?.length?<div className="audit-chat-attachments">{message.attachments.map(file=><AuditAttachment key={file.id} userId={user.id} file={file}/>)}</div>:null}{message.reasoning&&<details><summary>{ko?"추론 기록":"Reasoning"}</summary><pre>{message.reasoning}</pre></details>}<div className="audit-message-markdown"><ReactMarkdown remarkPlugins={[[remarkGfm,{singleTilde:true}],remarkMath]} rehypePlugins={[rehypeKatex]} components={{img:({src,alt})=><img src={mappedResource(user.id,src,true)} alt={alt||""}/>,a:({href,children})=><a href={mappedResource(user.id,href)} target="_blank" rel="noreferrer">{children}</a>}}>{message.content}</ReactMarkdown></div>{message.toolEvents?.length?<details><summary>{ko?"도구 기록":"Tool activity"}</summary><pre>{JSON.stringify(message.toolEvents,null,2)}</pre></details>:null}</article>)}{data&&branch&&!branch.messages.length&&<p className="audit-empty">{ko?"이 분기에 메시지가 없습니다.":"This branch has no messages."}</p>}</div></DialogFrame>;
}

export function AdminConversationsDialog({user,ko,onBack,onClose}:{user:AuditUser;ko:boolean;onBack:()=>void;onClose:()=>void}){
  const[page,setPage]=useState(1);const[data,setData]=useState<PageResult<ConversationSummary>>();const[notice,setNotice]=useState("");const[preview,setPreview]=useState("");
  useEffect(()=>{const controller=new AbortController();setData(undefined);fetch(`/api/users/${encodeURIComponent(user.id)}/audit?view=conversations&page=${page}&pageSize=20`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load conversations.");});return()=>controller.abort();},[page,user.id]);
  if(preview)return <ConversationViewDialog user={user} conversationId={preview} ko={ko} onBack={()=>setPreview("")} onClose={onClose}/>;
  return <DialogFrame title={ko?"채팅 기록":"Chat records"} subtitle={`${user.displayName} (@${user.username}) · ${ko?"모든 분기 포함":"all branches included"}`} ko={ko} onBack={onBack} onClose={onClose} footer={data&&<Pager page={data.page} pageCount={data.pageCount} total={data.total} ko={ko} onPage={setPage}/>}><div className="audit-browser-actions"><a className="subtle-action" href={`/api/users/${encodeURIComponent(user.id)}/audit?download=conversations`}><Download size={14}/>{ko?"전체 압축":"Export all"}</a></div>{notice&&<p className="settings-notice">{notice}</p>}<div className="audit-record-list">{data?.items.map(item=><article key={item.id}><div><strong>{item.title}</strong><small>{item.branchCount} {ko?"개 분기":"branches"} · {new Date(item.updatedAt).toLocaleString(ko?"ko-KR":"en-US")}</small></div><span><button onClick={()=>setPreview(item.id)} aria-label={`${item.title} ${ko?"보기":"View"}`}><Eye size={15}/></button><a href={`/api/users/${encodeURIComponent(user.id)}/audit?download=conversation&conversationId=${encodeURIComponent(item.id)}`} aria-label={`${item.title} ${ko?"다운로드":"Download"}`}><Download size={15}/></a></span></article>)}{data&&!data.items.length&&<p className="audit-empty">{ko?"채팅 기록이 없습니다.":"No chat records."}</p>}{!data&&!notice&&<div className="audit-loading"><LoaderCircle className="spin" size={20}/></div>}</div></DialogFrame>;
}

export function AdminFilesDialog({user,ko,onBack,onClose}:{user:AuditUser;ko:boolean;onBack:()=>void;onClose:()=>void}){
  const[page,setPage]=useState(1);const[sort,setSort]=useState("created_desc");const[layout,setLayout]=useState<"grid"|"list">("grid");const[data,setData]=useState<FilePage>();const[notice,setNotice]=useState("");
  useEffect(()=>{const controller=new AbortController();setData(undefined);fetch(`/api/users/${encodeURIComponent(user.id)}/audit?view=files&page=${page}&pageSize=24&sort=${encodeURIComponent(sort)}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load files.");});return()=>controller.abort();},[page,sort,user.id]);
  const sortOptions=[{value:"created_desc",label:ko?"생성일 · 최신순":"Created · newest"},{value:"created_asc",label:ko?"생성일 · 오래된순":"Created · oldest"},{value:"name_asc",label:ko?"파일명 · 오름차순":"Name · A–Z"},{value:"name_desc",label:ko?"파일명 · 내림차순":"Name · Z–A"},{value:"size_desc",label:ko?"크기 · 큰순":"Size · largest"},{value:"size_asc",label:ko?"크기 · 작은순":"Size · smallest"}];
  return <DialogFrame title={ko?"파일 저장소":"File storage"} subtitle={`${user.displayName} (@${user.username})${data?` · ${bytes(data.usedBytes)} / ${bytes(data.quotaBytes)}`:""}`} ko={ko} onBack={onBack} onClose={onClose} footer={data&&<Pager page={data.page} pageCount={data.pageCount} total={data.total} ko={ko} onPage={setPage}/>}><div className="audit-file-toolbar"><SelectMenu label={ko?"정렬":"Sort"} value={sort} options={sortOptions} onChange={value=>{setSort(value);setPage(1);}}/><span><button className={layout==="grid"?"active":""} onClick={()=>setLayout("grid")} aria-label={ko?"썸네일 보기":"Thumbnail view"}><Grid2X2 size={16}/></button><button className={layout==="list"?"active":""} onClick={()=>setLayout("list")} aria-label={ko?"목록 보기":"List view"}><List size={17}/></button><a href={`/api/users/${encodeURIComponent(user.id)}/audit?download=media`}><Download size={15}/>{ko?"전체 압축":"Export all"}</a></span></div>{notice&&<p className="settings-notice">{notice}</p>}<div className={`audit-file-browser ${layout}`}>{data?.files.map(file=><a key={file.id} href={resource(user.id,file.id)} title={file.name}>{file.mimeType.startsWith("image/")?<img src={resource(user.id,file.id,true,true)} alt={file.name} loading="lazy"/>:<span className="audit-generic-file"><FileText size={layout==="grid"?31:22}/></span>}<div><strong>{file.name}</strong><small>{file.mimeType}</small><small>{bytes(file.size)} · {new Date(file.createdAt).toLocaleString(ko?"ko-KR":"en-US")}</small></div><Download size={15}/></a>)}{data&&!data.files.length&&<p className="audit-empty">{ko?"저장된 파일이 없습니다.":"No stored files."}</p>}{!data&&!notice&&<div className="audit-loading"><LoaderCircle className="spin" size={20}/></div>}</div></DialogFrame>;
}
