"use client";

import { useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { ArrowLeft, ChevronLeft, ChevronRight, Download, Eye, FileText, Grid2X2, List, LoaderCircle, RotateCcw, Search, Trash2, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import type { Conversation, ConversationSummary, StorageFile, StoredAttachment } from "@/lib/types";
import { useModalFocus } from "@/lib/use-modal-focus";
import { SelectMenu } from "./select-menu";
import { ImageLightbox } from "./image-lightbox";

type AuditUser={id:string;username:string;displayName:string};
type PageResult<T>={items:T[];total:number;page:number;pageSize:number;pageCount:number;query:string;state:string};
type FilePage={files:StorageFile[];total:number;page:number;pageSize:number;pageCount:number;usedBytes:number;quotaBytes:number;trashUsedBytes:number;trashQuotaBytes:number;sort:string;query:string;state:string};
type ManagedConversation=Conversation&{deletedAt?:string};
const bytes=(value:number)=>value>=1024**3?`${(value/1024**3).toFixed(2)} GB`:value>=1024**2?`${(value/1024**2).toFixed(1)} MB`:`${Math.max(.1,value/1024).toFixed(1)} KB`;
const resource=(userId:string,id:string,inline=false,thumbnail=false)=>`/api/users/${encodeURIComponent(userId)}/audit?download=media-file&uploadId=${encodeURIComponent(id)}${inline?"&inline=1":""}${thumbnail?"&variant=thumbnail":""}`;
const mappedResource=(userId:string,value:unknown,inline=false)=>{const source=typeof value==="string"?value:"";const match=/^\/api\/uploads\/([a-zA-Z0-9_-]+)/.exec(source);return match?resource(userId,match[1],inline):source;};

function DialogFrame({title,subtitle,ko,onBack,onClose,children,footer,className=""}:{title:string;subtitle:string;ko:boolean;onBack?:()=>void;onClose:()=>void;children:React.ReactNode;footer?:React.ReactNode;className?:string}){
  const ref=useModalFocus(onClose);return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer managed-user-layer" role="dialog" aria-modal="true" aria-label={title}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><section className={`harness-dialog audit-browser-dialog ${className}`}><header><div className="audit-dialog-title">{onBack&&<button onClick={onBack} aria-label={ko?"뒤로":"Back"}><ArrowLeft size={18}/></button>}<div><h2>{title}</h2><p>{subtitle}</p></div></div><button onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>{children}{footer&&<footer>{footer}</footer>}</section></div>,document.body);
}

function Pager({page,pageCount,total,ko,onPage}:{page:number;pageCount:number;total:number;ko:boolean;onPage:(page:number)=>void}){return <nav className="audit-pager"><button disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={16}/></button><span>{page} / {pageCount}<small>{ko?`총 ${total}개`:`${total} total`}</small></span><button disabled={page>=pageCount} onClick={()=>onPage(page+1)}><ChevronRight size={16}/></button></nav>;}

function useLiveSearch(value:string,onSearch:(value:string)=>void){useEffect(()=>{const timer=window.setTimeout(()=>onSearch(value.trim()),180);return()=>window.clearTimeout(timer);},[onSearch,value]);}

function SearchField({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="audit-search"><Search size={15}/><input value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder}/></label>;}

async function auditMutation(userId:string,method:"PATCH"|"DELETE",resourceType:"conversation"|"file",id:string){const response=await fetch(`/api/users/${encodeURIComponent(userId)}/audit`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:resourceType,id,...(method==="PATCH"?{action:"restore"}:{})})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Audit operation failed.");}}

function AuditAttachment({userId,file,onPreview}:{userId:string;file:StoredAttachment;onPreview:(src:string,alt:string)=>void}){return <a className="audit-chat-attachment" href={resource(userId,file.id)} target="_blank" rel="noreferrer" onClick={event=>{if(file.mimeType.startsWith("image/")){event.preventDefault();onPreview(resource(userId,file.id,true),file.name);}}}>{file.mimeType.startsWith("image/")?<img src={resource(userId,file.id,true,true)} alt={file.name}/>:<FileText size={24}/>}<span><strong>{file.name}</strong><small>{bytes(file.size)}</small></span></a>;}

function ConversationViewDialog({user,conversationId,ko,onBack,onClose,onChanged}:{user:AuditUser;conversationId:string;ko:boolean;onBack:()=>void;onClose:()=>void;onChanged:()=>void}){
  const[data,setData]=useState<ManagedConversation>();const[branchId,setBranchId]=useState("");const[notice,setNotice]=useState("");const[preview,setPreview]=useState<{src:string;alt:string}>();
  useEffect(()=>{const controller=new AbortController();fetch(`/api/users/${encodeURIComponent(user.id)}/audit?view=conversation&conversationId=${encodeURIComponent(conversationId)}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);const conversation=body.conversation as ManagedConversation;setData(conversation);setBranchId(conversation.activeBranchId||conversation.branches[0]?.id||"");}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load conversation.");});return()=>controller.abort();},[conversationId,user.id]);
  const branch=data?.branches.find(item=>item.id===branchId)||data?.branches[0];
  async function change(method:"PATCH"|"DELETE"){if(method==="DELETE"&&!window.confirm(ko?"이 채팅을 영구 삭제할까요?":"Permanently delete this chat?"))return;try{await auditMutation(user.id,method,"conversation",conversationId);onChanged();onBack();}catch(error){setNotice(error instanceof Error?error.message:"Audit operation failed.");}}
  return <DialogFrame title={data?.title||(ko?"채팅 불러오는 중":"Loading conversation")} subtitle={`@${user.username}${data?` · ${data.branches.length} ${ko?"개 분기":"branches"}`:""}`} ko={ko} onBack={onBack} onClose={onClose} className="conversation-review-dialog"><div className="audit-review-toolbar">{data&&<SelectMenu label={ko?"분기":"Branch"} value={branch?.id||""} options={data.branches.map(item=>({value:item.id,label:item.name}))} onChange={setBranchId}/>}<span>{data?.deletedAt&&<><b className="deleted-badge">{ko?"삭제됨":"Deleted"}</b><button onClick={()=>void change("PATCH")}><RotateCcw size={14}/>{ko?"복원":"Restore"}</button><button className="danger" onClick={()=>void change("DELETE")}><Trash2 size={14}/>{ko?"영구 삭제":"Purge"}</button></>}<a className="subtle-action" href={`/api/users/${encodeURIComponent(user.id)}/audit?download=conversation&conversationId=${encodeURIComponent(conversationId)}`}><Download size={14}/>{ko?"압축 다운로드":"Download ZIP"}</a></span></div>{notice&&<p className="settings-notice">{notice}</p>}{!data&&!notice&&<div className="audit-loading"><LoaderCircle className="spin" size={20}/></div>}<div className="audit-conversation-view">{branch?.messages.map(message=><article key={message.id} className={message.role}><header><strong>{message.role==="user"?(ko?"사용자":"User"):(ko?"어시스턴트":"Assistant")}</strong><time>{new Date(message.createdAt).toLocaleString(ko?"ko-KR":"en-US")}</time></header>{message.attachments?.length?<div className="audit-chat-attachments">{message.attachments.map(file=><AuditAttachment key={file.id} userId={user.id} file={file} onPreview={(src,alt)=>setPreview({src,alt})}/>)}</div>:null}{message.reasoning&&<details><summary>{ko?"추론 기록":"Reasoning"}</summary><pre>{message.reasoning}</pre></details>}<div className="audit-message-markdown"><ReactMarkdown remarkPlugins={[[remarkGfm,{singleTilde:true}],remarkMath]} rehypePlugins={[rehypeKatex]} components={{img:({src,alt})=>{const mapped=mappedResource(user.id,src,true);return <img src={mapped} alt={alt||""} role="button" tabIndex={0} onClick={()=>setPreview({src:mapped,alt:alt||""})}/>;},a:({href,children})=><a href={mappedResource(user.id,href)} target="_blank" rel="noreferrer">{children}</a>}}>{message.content}</ReactMarkdown></div>{message.toolEvents?.length?<details><summary>{ko?"도구 기록":"Tool activity"}</summary><pre>{JSON.stringify(message.toolEvents,null,2)}</pre></details>:null}</article>)}</div>{preview&&<ImageLightbox src={preview.src} alt={preview.alt} onClose={()=>setPreview(undefined)}/>}</DialogFrame>;
}

export function AdminConversationsDialog({user,ko,onBack,onClose}:{user:AuditUser;ko:boolean;onBack:()=>void;onClose:()=>void}){
  const[page,setPage]=useState(1);const[data,setData]=useState<PageResult<ConversationSummary>>();const[notice,setNotice]=useState("");const[preview,setPreview]=useState("");const[query,setQuery]=useState("");const[search,setSearch]=useState("");const[state,setState]=useState("all");const[revision,setRevision]=useState(0);const commitSearch=useCallback((value:string)=>{setSearch(value);setPage(1);},[]);useLiveSearch(query,commitSearch);
  useEffect(()=>{const controller=new AbortController();setData(undefined);fetch(`/api/users/${encodeURIComponent(user.id)}/audit?view=conversations&page=${page}&q=${encodeURIComponent(search)}&state=${state}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load conversations.");});return()=>controller.abort();},[page,revision,search,state,user.id]);
  if(preview)return <ConversationViewDialog user={user} conversationId={preview} ko={ko} onBack={()=>setPreview("")} onClose={onClose} onChanged={()=>setRevision(value=>value+1)}/>;
  const states=[{value:"all",label:ko?"전체":"All"},{value:"active",label:ko?"사용 중":"Active"},{value:"deleted",label:ko?"삭제됨":"Deleted"}];
  return <DialogFrame title={ko?"채팅 기록":"Chat records"} subtitle={`${user.displayName} (@${user.username}) · ${ko?"모든 분기 포함":"all branches included"}`} ko={ko} onBack={onBack} onClose={onClose} footer={data&&<Pager page={data.page} pageCount={data.pageCount} total={data.total} ko={ko} onPage={setPage}/>}><div className="audit-browser-toolbar"><SearchField value={query} onChange={setQuery} placeholder={ko?"키워드, 모든 분기 또는 채팅 ID 검색":"Search keywords, all branches, or chat ID"}/><SelectMenu label={ko?"상태":"State"} value={state} options={states} onChange={value=>{setState(value);setPage(1);}}/><a className="subtle-action" href={`/api/users/${encodeURIComponent(user.id)}/audit?download=conversations`}><Download size={14}/>{ko?"전체 압축":"Export all"}</a></div>{notice&&<p className="settings-notice">{notice}</p>}<div className="audit-record-list">{data?.items.map(item=><article key={item.id} className={item.deletedAt?"deleted":""}><div><strong>{item.title}{item.deletedAt&&<b className="deleted-badge">{ko?"삭제됨":"Deleted"}</b>}</strong><small>{item.id} · {item.branchCount} {ko?"개 분기":"branches"} · {new Date(item.updatedAt).toLocaleString(ko?"ko-KR":"en-US")}</small></div><span><button onClick={()=>setPreview(item.id)}><Eye size={15}/></button><a href={`/api/users/${encodeURIComponent(user.id)}/audit?download=conversation&conversationId=${encodeURIComponent(item.id)}`}><Download size={15}/></a></span></article>)}{data&&!data.items.length&&<p className="audit-empty">{search?(ko?"검색 결과가 없습니다.":"No matching chats."):(ko?"채팅 기록이 없습니다.":"No chat records.")}</p>}{!data&&!notice&&<div className="audit-loading"><LoaderCircle className="spin" size={20}/></div>}</div></DialogFrame>;
}

export function AdminFilesDialog({user,ko,onBack,onClose}:{user:AuditUser;ko:boolean;onBack:()=>void;onClose:()=>void}){
  const[page,setPage]=useState(1);const[sort,setSort]=useState("created_desc");const[layout,setLayout]=useState<"grid"|"list">("grid");const[data,setData]=useState<FilePage>();const[notice,setNotice]=useState("");const[query,setQuery]=useState("");const[search,setSearch]=useState("");const[state,setState]=useState("all");const[revision,setRevision]=useState(0);const[preview,setPreview]=useState<{src:string;alt:string}>();const commitSearch=useCallback((value:string)=>{setSearch(value);setPage(1);},[]);useLiveSearch(query,commitSearch);
  useEffect(()=>{const controller=new AbortController();setData(undefined);fetch(`/api/users/${encodeURIComponent(user.id)}/audit?view=files&page=${page}&pageSize=24&sort=${encodeURIComponent(sort)}&q=${encodeURIComponent(search)}&state=${state}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load files.");});return()=>controller.abort();},[page,revision,search,sort,state,user.id]);
  async function change(file:StorageFile,method:"PATCH"|"DELETE"){if(method==="DELETE"&&!window.confirm(ko?`“${file.name}” 파일을 영구 삭제할까요?`:`Permanently delete “${file.name}”?`))return;try{await auditMutation(user.id,method,"file",file.id);setRevision(value=>value+1);}catch(error){setNotice(error instanceof Error?error.message:"Audit operation failed.");}}
  const sortOptions=[{value:"created_desc",label:ko?"생성일 · 최신순":"Created · newest"},{value:"created_asc",label:ko?"생성일 · 오래된순":"Created · oldest"},{value:"name_asc",label:ko?"파일명 · 오름차순":"Name · A–Z"},{value:"name_desc",label:ko?"파일명 · 내림차순":"Name · Z–A"},{value:"size_desc",label:ko?"크기 · 큰순":"Size · largest"},{value:"size_asc",label:ko?"크기 · 작은순":"Size · smallest"}];const states=[{value:"all",label:ko?"전체":"All"},{value:"active",label:ko?"사용 중":"Active"},{value:"deleted",label:ko?"삭제됨":"Deleted"}];
  return <DialogFrame title={ko?"파일 저장소":"File storage"} subtitle={`${user.displayName} (@${user.username})${data?` · ${bytes(data.usedBytes+data.trashUsedBytes)} / ${bytes(data.quotaBytes+data.trashQuotaBytes)}`:""}`} ko={ko} onBack={onBack} onClose={onClose} footer={data&&<Pager page={data.page} pageCount={data.pageCount} total={data.total} ko={ko} onPage={setPage}/>}><div className="audit-file-toolbar audit-browser-toolbar"><SearchField value={query} onChange={setQuery} placeholder={ko?"파일 이름 검색":"Search filenames"}/><SelectMenu label={ko?"상태":"State"} value={state} options={states} onChange={value=>{setState(value);setPage(1);}}/><SelectMenu label={ko?"정렬":"Sort"} value={sort} options={sortOptions} onChange={value=>{setSort(value);setPage(1);}}/><span><button className={layout==="grid"?"active":""} onClick={()=>setLayout("grid")}><Grid2X2 size={16}/></button><button className={layout==="list"?"active":""} onClick={()=>setLayout("list")}><List size={17}/></button><a href={`/api/users/${encodeURIComponent(user.id)}/audit?download=media`}><Download size={15}/>{ko?"전체 압축":"Export all"}</a></span></div>{notice&&<p className="settings-notice">{notice}</p>}<div className={`audit-file-browser ${layout}`}>{data?.files.map(file=><article key={file.id} className={file.deletedAt?"deleted":""}><button className="audit-file-preview" onClick={()=>file.mimeType.startsWith("image/")&&setPreview({src:resource(user.id,file.id,true),alt:file.name})}>{file.mimeType.startsWith("image/")?<img src={resource(user.id,file.id,true,true)} alt={file.name} loading="lazy"/>:<span className="audit-generic-file"><FileText size={layout==="grid"?31:22}/></span>}</button><div><strong>{file.name}{file.deletedAt&&<b className="deleted-badge">{ko?"삭제됨":"Deleted"}</b>}</strong><small>{file.mimeType}</small><small>{bytes(file.size)} · {new Date(file.createdAt).toLocaleString(ko?"ko-KR":"en-US")}</small></div><span className="audit-file-actions"><a href={resource(user.id,file.id)}><Download size={15}/></a>{file.deletedAt&&<><button onClick={()=>void change(file,"PATCH")} title={ko?"복원":"Restore"}><RotateCcw size={15}/></button><button className="danger" onClick={()=>void change(file,"DELETE")} title={ko?"영구 삭제":"Purge"}><Trash2 size={15}/></button></>}</span></article>)}{data&&!data.files.length&&<p className="audit-empty">{search?(ko?"검색 결과가 없습니다.":"No matching files."):(ko?"저장된 파일이 없습니다.":"No stored files.")}</p>}{!data&&!notice&&<div className="audit-loading"><LoaderCircle className="spin" size={20}/></div>}</div>{preview&&<ImageLightbox src={preview.src} alt={preview.alt} onClose={()=>setPreview(undefined)}/>}</DialogFrame>;
}
