"use client";
import { ChevronRight, Download, DatabaseBackup, LoaderCircle, RotateCcw, Users, X } from "lucide-react";
import { useRef, useState } from "react";
import { createPortal } from "react-dom";
import { SectionTitle } from "./section-title";
import { SelectMenu } from "./select-menu";
import { useModalFocus } from "@/lib/use-modal-focus";
import { useMessageDialog } from "./message-dialog";
import { roleLabel, UserDirectoryPager, UserDirectoryStatus, UserDirectoryToolbar, useUserDirectory } from "./user-directory";

type Scope="personal"|"global"|"accounts"|"user";type Mode="merge"|"replace";
const copy={ko:{backup:"백업 이미지 만들기",restore:"이미지 복원",merge:"병합",replace:"대체",working:"처리 중…",done:"복원이 완료되었습니다. 화면을 새로고침해 변경 내용을 반영합니다.",personal:"개인 백업 및 복원",personalDesc:"내 채팅, 미디어, 계정 설정과 모델 설정(커스텀 모델·추론 템플릿)을 로그인 정보로 암호화된 고압축 이미지로 보관합니다.",data:"데이터 관리",dataDesc:"전역 설정, 계정 인증 정보와 사용자별 이미지를 별도로 관리합니다.",global:"전역 설정",accounts:"모든 사용자 계정 인증 정보",users:"사용자 개별 이미지",open:"사용자 개별 이미지 관리 열기"},en:{backup:"Create backup image",restore:"Restore image",merge:"Merge",replace:"Replace",working:"Working…",done:"Restore completed. Reload to apply the changes.",personal:"Personal backup and restore",personalDesc:"Keep your chats, media, account settings, and model settings (custom models and reasoning templates) in one encrypted, highly compressed image protected by your login credentials.",data:"Data management",dataDesc:"Manage global settings, account credentials, and per-user images separately.",global:"Global settings",accounts:"All user account credentials",users:"Individual user images",open:"Open per-user image manager"}};

type ModelSettingsOutcome={status:"restored"|"absent"|"invalid"|"failed";aliases?:number;presets?:number;servedModels?:number;skipped?:number};
function modelSettingsNotice(outcome:ModelSettingsOutcome|undefined,ko:boolean){if(!outcome||outcome.status==="absent")return"";if(outcome.status==="invalid")return ko?"이미지의 모델 설정을 읽을 수 없어 건너뛰었습니다.":"The image's model settings could not be read and were skipped.";if(outcome.status==="failed")return ko?"모델 설정은 복원하지 못했습니다. 나머지 데이터는 복원되었습니다.":"Model settings could not be restored; the rest of the data was restored.";const{aliases=0,presets=0,servedModels=0,skipped=0}=outcome;const parts=ko?[`모델 설정: 커스텀 모델 ${aliases}개`,`추론 템플릿 ${presets}개`,...(servedModels?[`서빙 모델 ${servedModels}개`]:[])]:[`Model settings: ${aliases} custom model(s)`,`${presets} reasoning template(s)`,...(servedModels?[`${servedModels} served model(s)`]:[])];return`${parts.join(", ")}${ko?"를 복원했습니다.":" restored."}${skipped?(ko?` 이 워크스페이스에서 쓸 수 없는 ${skipped}개 항목은 건너뛰었습니다.`:` ${skipped} item(s) unavailable here were skipped.`):""}`;}
function CredentialDialog({ko,busy,restoring,onClose,onSubmit}:{ko:boolean;busy:boolean;restoring:boolean;onClose:()=>void;onSubmit:(username:string,password:string)=>void}) {
  const ref=useModalFocus(()=>{if(!busy)onClose();});const[username,setUsername]=useState("");const[password,setPassword]=useState("");
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer directory-layer" role="dialog" aria-modal="true" aria-label={ko?"백업 소유자 확인":"Backup owner credentials"}>
    <button className="settings-backdrop" tabIndex={-1} disabled={busy} onClick={onClose} aria-label={ko?"닫기":"Close"}/>
    <section className="harness-dialog backup-credentials-dialog"><header><h2>{ko?"백업 소유자 확인":"Backup owner credentials"}</h2><button disabled={busy} onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
      <form onSubmit={event=>{event.preventDefault();onSubmit(username,password);}}>
        <p>{ko?(restoring?"백업 당시 소유자의 아이디와 비밀번호를 입력하세요. 다른 인스턴스에서도 복원할 수 있습니다.":"개인·사용자별 백업은 해당 사용자의 로그인 정보, 전역·전체 계정 백업은 실행하는 관리자의 로그인 정보로 암호화합니다."):(restoring?"Enter the owner's username and password from when the backup was created. You can restore on another instance.":"Personal and per-user backups use that user's credentials. Global and account backups use the administrator's credentials.")}</p>
        <label>{ko?"아이디":"Username"}<input autoComplete="off" required disabled={busy} value={username} onChange={event=>setUsername(event.target.value)}/></label>
        <label>{ko?"비밀번호":"Password"}<input type="password" autoComplete="off" required maxLength={200} disabled={busy} value={password} onChange={event=>setPassword(event.target.value)}/></label>
        <p>{ko?"복원에는 백업 당시의 비밀번호가 필요합니다. 로그인 비밀번호를 바꾸더라도 기존 백업의 암호는 바뀌지 않습니다.":"Keep the password used at backup time. Changing your login password does not change existing backups."}</p>
        <footer><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>{ko?"취소":"Cancel"}</button><button className="save-button" disabled={busy}>{busy?<LoaderCircle className="spin" size={15}/>:null}{busy?(ko?"처리 중…":"Working…"):(restoring?(ko?"복원":"Restore"):(ko?"암호화 백업":"Encrypted backup"))}</button></footer>
      </form>
    </section>
  </div>,document.body);
}
function BackupCard({scope,title,description,ko,userId,onNotice}:{scope:Scope;title:string;description:string;ko:boolean;userId?:string;onNotice:(value:string)=>void}) {
  const c=ko?copy.ko:copy.en;const input=useRef<HTMLInputElement>(null);const[mode,setMode]=useState<Mode>("merge");const[busy,setBusy]=useState(false);const[action,setAction]=useState<{file?:File}|null>(null);const{dialog,confirm}=useMessageDialog(ko);
  async function run(username:string,password:string){if(!action||busy)return;const file=action.file;
    if(file&&mode==="replace"&&!await confirm({tone:"danger",title:ko?"대체 복원":"Replace restore",message:ko?"기존 데이터를 삭제하고 이미지로 대체할까요?":"Delete existing data and replace it with this image?",detail:ko?"전체 계정 복원은 현재 작업 중인 최고 관리자 계정을 유지합니다.":"Account restore retains the destination superadmin performing this operation.",confirmLabel:ko?"삭제 후 복원":"Delete and restore"}))return;
    setBusy(true);onNotice("");try{const headers={"X-Backup-Credentials":encodeURIComponent(JSON.stringify({username,password})),"X-Backup-Scope":scope,"X-Restore-Mode":mode,...(userId?{"X-Target-User-Id":userId}:{})};
      const params=new URLSearchParams({scope,...(userId?{userId}:{})});const response=await fetch(file?"/api/backup":`/api/backup?${params}`,{method:file?"POST":"GET",headers, ...(file?{body:file}:{})});
      if(!response.ok){const result=await response.json();throw new Error(result.error||"Backup failed");}
      if(file){const result=await response.json();onNotice([c.done,modelSettingsNotice(result.modelSettings,ko)].filter(Boolean).join(" "));}else{const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=response.headers.get("Content-Disposition")?.match(/filename="([^"]+)"/)?.[1]||"NeuralNetUI.nnbak";link.click();setTimeout(()=>URL.revokeObjectURL(url),60_000);onNotice(ko?"암호화된 백업을 저장했습니다.":"Encrypted backup downloaded.");}setAction(null);
    }catch(error){onNotice(error instanceof Error?error.message:(ko?"처리하지 못했습니다.":"Operation failed."));setAction(null);}finally{setBusy(false);}}
  return <article className="backup-card"><div><strong>{title}</strong><small>{description}</small></div><div className="backup-card-actions"><button className="secondary-button" disabled={busy} onClick={()=>setAction({})}><Download size={15}/>{c.backup}</button><div className="backup-restore-control"><SelectMenu label={ko?"복원 방식":"Restore mode"} value={mode} options={[{value:"merge",label:c.merge},{value:"replace",label:c.replace}]} onChange={value=>setMode(value as Mode)}/><button className={mode==="replace"?"danger-button":"secondary-button"} disabled={busy} onClick={()=>input.current?.click()}><RotateCcw size={15}/>{c.restore}</button><input ref={input} hidden type="file" accept=".nnbak" onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)setAction({file});}}/></div></div>{action&&<CredentialDialog ko={ko} busy={busy} restoring={Boolean(action.file)} onClose={()=>setAction(null)} onSubmit={run}/>} {dialog}</article>;
}

function UserImagesDialog({ko,onClose}:{ko:boolean;onClose:()=>void}){const c=ko?copy.ko:copy.en;const ref=useModalFocus(onClose);const directory=useUserDirectory();const[notice,setNotice]=useState("");return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer directory-layer" role="dialog" aria-modal="true" aria-label={c.users}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><section className="harness-dialog directory-dialog backup-users-dialog"><header><div><h2>{c.users}</h2><p>{ko?"사용자마다 독립된 전체 데이터 이미지를 백업하거나 복원합니다.":"Back up or restore a complete, isolated image for each user."}</p></div><button title={ko?"닫기":"Close"} aria-label={ko?"닫기":"Close"} onClick={onClose}><X size={20}/></button></header><UserDirectoryToolbar directory={directory} ko={ko}/>{notice&&<p className="settings-notice" role="status">{notice}</p>}<div className="directory-list backup-user-list">{directory.users.map(user=><BackupCard key={user.id} scope="user" userId={user.id} ko={ko} title={user.displayName} description={`@${user.username} · ${roleLabel(user.role,ko)}`} onNotice={setNotice}/>)}</div><UserDirectoryStatus directory={directory} ko={ko}/><UserDirectoryPager directory={directory} ko={ko}/></section></div>,document.body);}

export function AccountBackupSettings({ko}:{ko:boolean}){const c=ko?copy.ko:copy.en;const[notice,setNotice]=useState("");return <section className="settings-section backup-settings"><SectionTitle icon={<DatabaseBackup size={19}/>} title={c.personal} description={c.personalDesc}/><BackupCard scope="personal" title={c.personal} description={ko?"이미지 버전은 복원 시 자동 검사되며 이전 버전은 승계 어댑터를 거칩니다.":"Image versions are checked during restore; older images pass through sequential adapters."} ko={ko} onNotice={setNotice}/>{notice&&<p className="settings-notice" role="status">{notice}</p>}</section>;}
export function DataManagementSettings({ko}:{ko:boolean}){const c=ko?copy.ko:copy.en;const[notice,setNotice]=useState(""),[users,setUsers]=useState(false);return <section className="settings-section backup-settings"><SectionTitle icon={<DatabaseBackup size={19}/>} title={c.data} description={c.dataDesc}/><BackupCard scope="global" title={c.global} description={ko?"서버 연결, 모델, 도구 및 워크스페이스 설정":"Connections, models, tools, and workspace configuration"} ko={ko} onNotice={setNotice}/><BackupCard scope="accounts" title={c.accounts} description={ko?"비밀번호 해시, 역할, 플랜 연결 및 계정 설정":"Password hashes, roles, plan assignments, and account settings"} ko={ko} onNotice={setNotice}/><button className="user-manager-launch" onClick={()=>setUsers(true)}><Users size={17}/><span>{c.open}</span><ChevronRight size={17}/></button>{notice&&<p className="settings-notice" role="status">{notice}</p>}{users&&<UserImagesDialog ko={ko} onClose={()=>setUsers(false)}/>}</section>;}
