"use client";
import { Download, DatabaseBackup, LoaderCircle, RotateCcw, Users, X, ChevronLeft, ChevronRight } from "lucide-react";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import type { UserSummary } from "@/lib/types";
import { SectionTitle } from "./section-title";
import { SelectMenu } from "./select-menu";
import { useModalFocus } from "@/lib/use-modal-focus";
import { useMessageDialog } from "./message-dialog";

type Scope="personal"|"global"|"accounts"|"user";type Mode="merge"|"replace";
const copy={ko:{backup:"백업 이미지 만들기",restore:"이미지 복원",merge:"병합",replace:"대체",working:"처리 중…",done:"복원이 완료되었습니다. 화면을 새로고침해 변경 내용을 반영합니다.",personal:"개인 백업 및 복원",personalDesc:"내 채팅, 미디어와 계정 설정을 고압축 7z 이미지로 보관합니다. 비밀번호는 포함하지 않습니다.",data:"데이터 관리",dataDesc:"전역 설정, 계정 인증 정보와 사용자별 이미지를 별도로 관리합니다.",global:"전역 설정",accounts:"모든 사용자 계정 인증 정보",users:"사용자 개별 이미지",open:"이미지 관리 열기"},en:{backup:"Create backup image",restore:"Restore image",merge:"Merge",replace:"Replace",working:"Working…",done:"Restore completed. Reload to apply the changes.",personal:"Personal backup and restore",personalDesc:"Keep your chats, media, and account settings in one highly compressed 7z image. Passwords are excluded.",data:"Data management",dataDesc:"Manage global settings, account credentials, and per-user images separately.",global:"Global settings",accounts:"All user account credentials",users:"Individual user images",open:"Open image manager"}};

function download(scope:Scope,userId?:string){const params=new URLSearchParams({scope});if(userId)params.set("userId",userId);window.location.href=`/api/backup?${params}`;}
function RestoreControl({scope,userId,ko,onDone}:{scope:Scope;userId?:string;ko:boolean;onDone:(text:string)=>void}){const c=ko?copy.ko:copy.en;const input=useRef<HTMLInputElement>(null);const[mode,setMode]=useState<Mode>("merge");const[busy,setBusy]=useState(false);const{dialog,confirm}=useMessageDialog(ko);async function pick(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(mode==="replace"&&!await confirm({tone:"danger",title:ko?"대체 복원":"Replace restore",message:ko?"기존 데이터를 삭제하고 이미지로 대체할까요?":"Delete existing data and replace it with this image?",detail:ko?"이 작업은 되돌릴 수 없습니다.":"This action cannot be undone.",confirmLabel:ko?"삭제 후 복원":"Delete and restore"}))return;setBusy(true);try{const response=await fetch("/api/backup",{method:"POST",headers:{"Content-Type":"application/x-7z-compressed","X-Backup-Scope":scope,"X-Restore-Mode":mode,...(userId?{"X-Target-User-Id":userId}:{})},body:file});const body=await response.json();if(!response.ok)throw new Error(body.error);onDone(c.done);}catch(error){onDone(error instanceof Error?error.message:"Restore failed.");}finally{setBusy(false);}}return <>{dialog}<div className="backup-restore-control"><SelectMenu label={ko?"복원 방식":"Restore mode"} value={mode} options={[{value:"merge",label:c.merge},{value:"replace",label:c.replace}]} onChange={value=>setMode(value as Mode)}/><button className={mode==="replace"?"danger-button":"secondary-button"} disabled={busy} onClick={()=>input.current?.click()}>{busy?<LoaderCircle className="spin" size={15}/>:<RotateCcw size={15}/>} {busy?c.working:c.restore}</button><input ref={input} hidden type="file" accept=".7z,application/x-7z-compressed" onChange={pick}/></div></>;}
function BackupCard({scope,title,description,ko,userId,onNotice}:{scope:Scope;title:string;description:string;ko:boolean;userId?:string;onNotice:(value:string)=>void}){const c=ko?copy.ko:copy.en;return <article className="backup-card"><div><strong>{title}</strong><small>{description}</small></div><div className="backup-card-actions"><button className="secondary-button" onClick={()=>download(scope,userId)}><Download size={15}/>{c.backup}</button><RestoreControl scope={scope} userId={userId} ko={ko} onDone={onNotice}/></div></article>;}

function UserImagesDialog({ko,onClose}:{ko:boolean;onClose:()=>void}){const c=ko?copy.ko:copy.en;const ref=useModalFocus(onClose);const[users,setUsers]=useState<UserSummary[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[notice,setNotice]=useState("");useEffect(()=>{fetch(`/api/users?page=${page}`,{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setUsers(body.users);setPages(body.pageCount);}).catch(error=>setNotice(error instanceof Error?error.message:"Unable to load users."));},[page]);return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer" role="dialog" aria-modal="true" aria-label={c.users}><button className="settings-backdrop" onClick={onClose}/><section className="harness-dialog backup-users-dialog"><header><div><h2>{c.users}</h2><p>{ko?"사용자마다 독립된 전체 데이터 이미지를 백업하거나 복원합니다.":"Back up or restore a complete, isolated image for each user."}</p></div><button onClick={onClose}><X size={20}/></button></header>{notice&&<p className="settings-notice">{notice}</p>}<div className="backup-user-list">{users.map(user=><BackupCard key={user.id} scope="user" userId={user.id} ko={ko} title={`${user.displayName} (@${user.username})`} description={user.role} onNotice={setNotice}/>)}</div><nav className="audit-pager"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft size={16}/></button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)}><ChevronRight size={16}/></button></nav></section></div>,document.body);}

export function AccountBackupSettings({ko}:{ko:boolean}){const c=ko?copy.ko:copy.en;const[notice,setNotice]=useState("");return <section className="settings-section backup-settings"><SectionTitle icon={<DatabaseBackup size={19}/>} title={c.personal} description={c.personalDesc}/><BackupCard scope="personal" title={c.personal} description={ko?"이미지 버전은 복원 시 자동 검사되며 이전 버전은 승계 어댑터를 거칩니다.":"Image versions are checked during restore; older images pass through sequential adapters."} ko={ko} onNotice={setNotice}/>{notice&&<p className="settings-notice" role="status">{notice}</p>}</section>;}
export function DataManagementSettings({ko}:{ko:boolean}){const c=ko?copy.ko:copy.en;const[notice,setNotice]=useState(""),[users,setUsers]=useState(false);return <section className="settings-section backup-settings"><SectionTitle icon={<DatabaseBackup size={19}/>} title={c.data} description={c.dataDesc}/><BackupCard scope="global" title={c.global} description={ko?"서버 연결, 모델, 도구 및 워크스페이스 설정":"Connections, models, tools, and workspace configuration"} ko={ko} onNotice={setNotice}/><BackupCard scope="accounts" title={c.accounts} description={ko?"비밀번호 해시, 역할, 플랜 연결 및 계정 설정":"Password hashes, roles, plan assignments, and account settings"} ko={ko} onNotice={setNotice}/><button className="user-manager-launch" onClick={()=>setUsers(true)}><Users size={17}/>{c.open}</button>{notice&&<p className="settings-notice" role="status">{notice}</p>}{users&&<UserImagesDialog ko={ko} onClose={()=>setUsers(false)}/>}</section>;}
