"use client";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronLeft, ChevronRight, Clock3, LoaderCircle, Search, Trash2, X } from "lucide-react";
import type { ConversationSummary } from "@/lib/types";
import { useModalFocus } from "@/lib/use-modal-focus";
import { SelectMenu } from "./select-menu";
import { useMessageDialog } from "./message-dialog";

type State={items:ConversationSummary[];total:number;page:number;pageSize:number;pageCount:number;query:string;inactiveHours:number};
async function jsonResponse(response:Response){let body;try{body=await response.json();}catch(error){if(response.ok)throw error;body={};}if(!response.ok)throw new Error(body.error||`Request failed (${response.status}).`);return body;}

export function ChatManager({ko,onClose,onOpenConversation,onDeleted}:{ko:boolean;onClose:()=>void;onOpenConversation:(id:string)=>void;onDeleted:(ids:string[]|"filtered")=>void}){
  const ref=useModalFocus(onClose);const[state,setState]=useState<State>();const[page,setPage]=useState(1);const[query,setQuery]=useState("");const[search,setSearch]=useState("");const[age,setAge]=useState(0);const[unit,setUnit]=useState<"hours"|"days">("days");const[selectionMode,setSelectionMode]=useState(false);const[selected,setSelected]=useState<Record<string,boolean>>({});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[revision,setRevision]=useState(0);
  const{dialog:messageDialog,confirm:askConfirm}=useMessageDialog(ko);
  const inactiveHours=age>0?Math.max(1,Math.floor(age))*(unit==="days"?24:1):0;
  useEffect(()=>{const timer=window.setTimeout(()=>{setSearch(query.trim());setPage(1);},180);return()=>window.clearTimeout(timer);},[query]);
  useEffect(()=>{setPage(1);},[inactiveHours]);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/conversations?manage=1&page=${page}&pageSize=10&q=${encodeURIComponent(search)}&inactiveHours=${inactiveHours}`,{cache:"no-store",signal:controller.signal}).then(jsonResponse).then(body=>{setState(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Unable to load chats.");});return()=>controller.abort();},[inactiveHours,page,revision,search]);
  const selectedIds=Object.entries(selected).filter(([,value])=>value).map(([id])=>id);
  function toggle(id:string){setSelected(current=>({...current,[id]:!current[id]}));}
  function togglePage(){const items=state?.items||[];const all=items.length>0&&items.every(item=>selected[item.id]);setSelected(current=>{const next={...current};for(const item of items)next[item.id]=!all;return next;});}
  async function remove(ids:string[]|"filtered"){
    const count=ids==="filtered"?state?.total||0:ids.length;if(!count||busy)return;
    const message=ids==="filtered"?(ko?`현재 검색 및 기간 조건에 맞는 채팅 ${count}개를 모두 삭제할까요?`:`Delete all ${count} chat(s) matching the current filters?`):(ko?`선택한 채팅 ${count}개를 삭제할까요?`:`Delete ${count} selected chat(s)?`);if(!await askConfirm({tone:"danger",title:ko?"채팅 삭제":"Delete chats",message,detail:ids==="filtered"?(ko?"현재 조건에 맞는 모든 채팅이 삭제됩니다.":"Every chat matching the current filters is deleted."):undefined,confirmLabel:ko?"삭제":"Delete"}))return;
    setBusy(true);setNotice("");try{await jsonResponse(await fetch("/api/conversations",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify(ids==="filtered"?{filter:{query:search,inactiveHours}}:{ids})}));onDeleted(ids);setSelected({});setRevision(value=>value+1);setNotice(ko?`${count}개 채팅을 삭제했습니다.`:`Deleted ${count} chat(s).`);}catch(error){setNotice(error instanceof Error?error.message:"Unable to delete chats.");}finally{setBusy(false);}
  }
  const unitOptions=[{value:"hours",label:ko?"시간":"Hours"},{value:"days",label:ko?"일":"Days"}];
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer chat-manager-layer" role="dialog" aria-modal="true" aria-label={ko?"채팅 관리하기":"Manage chats"}><button className="settings-backdrop" tabIndex={-1} onClick={onClose}/><section className="harness-dialog chat-manager-dialog"><header><div><h2>{ko?"채팅 관리하기":"Manage chats"}</h2><p>{ko?"채팅을 검색하거나 마지막 활동 시점으로 걸러 선택 또는 일괄 삭제합니다.":"Search chats or filter by last activity, then delete selected or matching chats."}</p></div><button onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
    <div className="chat-manager-filters"><label className="chat-manager-search"><Search size={15}/><input data-autofocus value={query} onChange={event=>setQuery(event.target.value)} placeholder={ko?"제목, 내용 또는 채팅 ID 검색":"Search titles, content, or chat IDs"}/></label><div className="chat-age-filter"><Clock3 size={15}/><span>{ko?"마지막 채팅 후":"Inactive for"}</span><input type="number" min={0} max={unit==="days"?7300:175200} step={1} value={age} onChange={event=>setAge(Math.max(0,Number(event.target.value)||0))}/><SelectMenu label={ko?"기간 단위":"Age unit"} value={unit} options={unitOptions} onChange={value=>setUnit(value as "hours"|"days")}/></div></div>
    <div className="chat-manager-actions"><button className={`storage-action-button ${selectionMode?"active":""}`} onClick={()=>{setSelectionMode(value=>!value);setSelected({});}}><Check size={15}/>{selectionMode?(ko?"선택 종료":"Finish selecting"):(ko?"선택 삭제":"Select chats")}</button>{selectionMode&&<button className="storage-action-button" onClick={togglePage}><Check size={15}/>{state?.items.every(item=>selected[item.id])?(ko?"현재 페이지 해제":"Deselect page"):(ko?"현재 페이지 선택":"Select page")}</button>}<button className="danger-action compact" disabled={!state?.total||busy} onClick={()=>void remove("filtered")}><Trash2 size={15}/>{ko?`조건에 맞는 채팅 일괄 삭제 (${state?.total||0})`:`Delete matching chats (${state?.total||0})`}</button></div>
    {selectionMode&&<div className="storage-delete-toolbar"><span><Check size={15}/><strong>{ko?`${selectedIds.length}개 선택됨`:`${selectedIds.length} selected`}</strong><small>{ko?"여러 페이지에서 선택할 수 있습니다.":"Selections can span pages."}</small></span><button className="danger" disabled={!selectedIds.length||busy} onClick={()=>void remove(selectedIds)}>{busy?<LoaderCircle className="spin" size={15}/>:<Trash2 size={15}/>} {ko?"선택 채팅 삭제":"Delete selected"}</button></div>}
    {messageDialog}{notice&&<p className="settings-notice" role="status">{notice}</p>}
    {!state?<div className="storage-loading"><LoaderCircle className="spin" size={20}/></div>:<div className="chat-manager-list">{state.items.map(item=><article key={item.id} className={selected[item.id]?"selected":""}><button className="chat-manager-open" aria-pressed={selectionMode?Boolean(selected[item.id]):undefined} onClick={()=>selectionMode?toggle(item.id):onOpenConversation(item.id)}><span><strong>{item.title}</strong><small>{new Date(item.updatedAt).toLocaleString(ko?"ko-KR":"en-US")} · {ko?`${item.branchCount}개 분기`:`${item.branchCount} branch(es)`}</small></span></button>{selectionMode&&<button className={`circle-check ${selected[item.id]?"selected":""}`} aria-pressed={Boolean(selected[item.id])} aria-label={`${selected[item.id]?(ko?"선택 해제":"Deselect"):(ko?"선택":"Select")}: ${item.title}`} onClick={()=>toggle(item.id)}>{selected[item.id]&&<Check size={16}/>}</button>}</article>)}{!state.items.length&&<p className="storage-empty">{ko?"조건에 맞는 채팅이 없습니다.":"No chats match these filters."}</p>}</div>}
    {state&&<nav className="audit-pager"><button disabled={state.page<=1} onClick={()=>setPage(state.page-1)}><ChevronLeft size={16}/></button><span>{state.page} / {state.pageCount}<small>{ko?`총 ${state.total}개`:`${state.total} total`}</small></span><button disabled={state.page>=state.pageCount} onClick={()=>setPage(state.page+1)}><ChevronRight size={16}/></button></nav>}
  </section></div>,document.body);
}
