"use client";
import { Check, ChevronRight, Clock3, Gauge, HardDrive, Layers, Plus, Save, Trash2, TicketCheck, UserPlus, Users } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { ModelConfig, UsagePlan } from "@/lib/types";
import { SectionTitle } from "./section-title";
import { SelectMenu } from "./select-menu";
import { useMessageDialog } from "./message-dialog";
import { PlanUsersDialog, UserPickerDialog, type PickedUser } from "./user-directory";

const GB=1024**3;
const newPlan=():UsagePlan=>({id:"",name:"",servedModelIds:[],modelWeights:{},tokenLimits:[],storageQuotaBytes:512*1024**2,trashQuotaBytes:1024**3});
const gbValue=(bytes:number)=>Number((bytes/GB).toFixed(3));
export function PlanSettings({models,ko}:{models:ModelConfig[];ko:boolean}){const[plans,setPlans]=useState<UsagePlan[]>([]),[activeId,setActiveId]=useState(""),[draft,setDraft]=useState<UsagePlan>(newPlan),[notice,setNotice]=useState(""),[usersOpen,setUsersOpen]=useState(false);const[creditMode,setCreditMode]=useState<"plan"|"user">("plan"),[creditPlan,setCreditPlan]=useState(""),[creditUsers,setCreditUsers]=useState<Map<string,PickedUser>>(new Map()),[pickerOpen,setPickerOpen]=useState(false),[creditHours,setCreditHours]=useState(5),[creditExpiry,setCreditExpiry]=useState(""),[creditTitle,setCreditTitle]=useState(""),[creditNotice,setCreditNotice]=useState("");const{dialog,confirm}=useMessageDialog(ko);const modelList=useMemo(()=>models.filter(model=>!model.isAlias),[models]);
  async function loadPlans(preferred?:string){const response=await fetch("/api/plans",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error);setPlans(body.plans);setCreditPlan(current=>current||body.plans[0]?.id||"");const id=preferred??(activeId||body.plans[0]?.id||"");setActiveId(id);setDraft(structuredClone(body.plans.find((plan:UsagePlan)=>plan.id===id)||newPlan()));}
  useEffect(()=>{void loadPlans().catch(error=>setNotice(error.message));},[]);
  async function refreshCounts(){const response=await fetch("/api/plans",{cache:"no-store"});if(response.ok)setPlans((await response.json()).plans);}
  function choose(id:string){setNotice("");setActiveId(id);setDraft(structuredClone(plans.find(plan=>plan.id===id)||newPlan()));}
  async function save(){setNotice("");const response=await fetch(draft.id?`/api/plans/${draft.id}`:"/api/plans",{method:draft.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}),body=await response.json();if(!response.ok){setNotice(body.error);return;}await loadPlans(body.plan.id);setNotice(ko?"플랜을 저장했습니다.":"Plan saved.");}
  async function remove(){if(!draft.id)return;if(!await confirm({tone:"danger",title:ko?"플랜 삭제":"Delete plan",message:ko?`${draft.name} 플랜을 삭제할까요?`:`Delete the ${draft.name} plan?`,detail:ko?"이 플랜을 쓰던 사용자는 저장소 용량이 가장 큰 다른 플랜으로 옮겨집니다. 이 작업은 되돌릴 수 없습니다.":"Its users move to the remaining plan with the most storage. This action cannot be undone.",confirmLabel:ko?"삭제":"Delete"}))return;const response=await fetch(`/api/plans/${draft.id}`,{method:"DELETE"}),body=await response.json();if(!response.ok){setNotice(body.error);return;}await loadPlans("");setNotice(ko?"플랜을 삭제했습니다.":"Plan deleted.");}
  function addLimit(){setDraft(current=>({...current,tokenLimits:[...current.tokenLimits,{id:crypto.randomUUID(),durationSeconds:3*3600,tokenLimit:100000,tokenScope:"both"}]}));}
  const updateLimit=(index:number,patch:Partial<UsagePlan["tokenLimits"][number]>)=>setDraft(current=>({...current,tokenLimits:current.tokenLimits.map((item,i)=>i===index?{...item,...patch}:item)}));
  async function grant(event:FormEvent){event.preventDefault();setCreditNotice("");const targets=creditMode==="plan"?{targetType:"plan",targetId:creditPlan}:{targetType:"user",targetIds:[...creditUsers.keys()]};const response=await fetch("/api/reset-credits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...targets,maxWindowSeconds:Math.round(creditHours*3600),expiresAt:creditExpiry,title:creditTitle})}),body=await response.json();if(!response.ok){setCreditNotice(body.error);return;}setCreditTitle("");const count=body.credits?.length||1;setCreditNotice(creditMode==="plan"?(ko?`${plans.find(plan=>plan.id===creditPlan)?.name} 플랜에 리셋권을 지급했습니다.`:"Reset credit granted to the plan."):(ko?`${count}명에게 리셋권을 지급했습니다.`:`Reset credit granted to ${count} user(s).`));if(creditMode==="user")setCreditUsers(new Map());}
  const picked=[...creditUsers.values()];const creditReady=(creditMode==="plan"?Boolean(creditPlan):picked.length>0)&&creditTitle.trim()&&creditExpiry&&creditHours>=1;
  const allEnabled=draft.servedModelIds.length===0;
  return <div className="settings-section wide plan-settings">{dialog}<SectionTitle icon={<Gauge size={19}/>} title={ko?"플랜 설정":"Plan settings"} description={ko?"모델 접근, 토큰 시간 구간, 모델별 가중치와 저장소를 관리합니다.":"Manage model access, token windows, per-model weights, and storage."}/>
    <div className="plan-layout"><aside className="plan-list" aria-label={ko?"플랜 목록":"Plans"}><button className={`plan-list-new ${activeId===""?"active":""}`} onClick={()=>choose("")}><Plus size={15}/><span>{ko?"새 플랜":"New plan"}</span></button>{plans.map(plan=><button className={activeId===plan.id?"active":""} aria-current={activeId===plan.id} key={plan.id} onClick={()=>choose(plan.id)}><Layers size={15}/><span><strong>{plan.name}</strong><small>{ko?`${plan.userCount||0}명 사용 중`:`${plan.userCount||0} users`}</small></span></button>)}</aside>
      <div className="plan-editor">
        <label className="field plan-name-field"><span>{ko?"플랜 이름":"Plan name"}</span><input value={draft.name} maxLength={80} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder={ko?"예: Free, Pro":"e.g. Free, Pro"}/></label>
        <section className="plan-block"><div className="plan-block-title"><HardDrive size={17}/><div><h4>{ko?"저장소 용량":"Storage capacity"}</h4><p>{ko?"플랜을 쓰는 모든 사용자에게 저장 즉시 적용됩니다. 휴지통은 삭제된 파일이 보관되는 공간입니다.":"Applied to every user on this plan when saved. Trash holds deleted files until retention ends."}</p></div></div><div className="plan-quota-grid"><label className="field"><span>{ko?"저장소":"Storage"}</span><span className="unit-input"><input type="number" min={.001} max={10240} step={.25} value={gbValue(draft.storageQuotaBytes)} onChange={event=>setDraft({...draft,storageQuotaBytes:Math.max(1024**2,Math.round(Number(event.target.value)*GB))})}/><em>GB</em></span></label><label className="field"><span>{ko?"휴지통":"Trash"}</span><span className="unit-input"><input type="number" min={.001} max={20480} step={.25} value={gbValue(draft.trashQuotaBytes)} onChange={event=>setDraft({...draft,trashQuotaBytes:Math.max(1024**2,Math.round(Number(event.target.value)*GB))})}/><em>GB</em></span></label></div></section>
        <section className="plan-block"><div className="plan-block-title"><Layers size={17}/><div><h4>{ko?"서빙 모델":"Serving models"}</h4><p>{ko?"끈 모델은 이 플랜에서 선택할 수 없습니다. 가중치는 해당 모델의 토큰 사용량에 곱해집니다.":"Disabled models are unavailable on this plan. Weights multiply that model's token usage."}</p></div></div>{modelList.length?<div className="plan-models">{modelList.map(model=>{const enabled=allEnabled||draft.servedModelIds.includes(model.id);return <div key={model.id} className={enabled?"":"off"}><button role="switch" aria-checked={enabled} aria-label={ko?`${model.name} 사용`:`Allow ${model.name}`} className={`toggle ${enabled?"on":""}`} onClick={()=>setDraft(current=>{const currentEnabled=current.servedModelIds.length===0?modelList.map(item=>item.id):current.servedModelIds;return{...current,servedModelIds:currentEnabled.includes(model.id)?currentEnabled.filter(id=>id!==model.id):[...currentEnabled,model.id]};})}><i/></button><span><strong>{model.name}</strong><small>{model.id}</small></span><label><span>{ko?"가중치":"Weight"}</span><span className="weight-input"><input type="number" min={.01} max={100} step={.1} value={draft.modelWeights[model.id]||1} onChange={event=>setDraft(current=>({...current,modelWeights:{...current.modelWeights,[model.id]:Number(event.target.value)}}))}/><em>×</em></span></label></div>})}</div>:<p className="audit-empty">{ko?"서빙 중인 모델이 없습니다.":"No served models."}</p>}</section>
        <section className="plan-block"><div className="plan-block-title"><Clock3 size={17}/><div><h4>{ko?"토큰 사용량 제한":"Token usage limits"}</h4><p>{ko?"첫 사용 시점을 기준으로 각 시간 구간이 시작됩니다.":"Each time window starts with the first use."}</p></div><button className="subtle-action" onClick={addLimit}><Plus size={14}/>{ko?"한도 추가":"Add limit"}</button></div>
          {draft.tokenLimits.length?<div className="plan-limits"><div className="plan-limit-head" aria-hidden="true"><span>{ko?"시간 구간":"Window"}</span><span>{ko?"토큰 한도":"Token limit"}</span><span>{ko?"계산 대상":"Counts"}</span><span/></div>{draft.tokenLimits.map((limit,index)=><div className="plan-limit-row" key={limit.id}><label className="unit-input"><span className="visually-hidden">{ko?"시간 구간":"Window"}</span><input type="number" min={1} max={8760} value={limit.durationSeconds/3600} onChange={event=>updateLimit(index,{durationSeconds:Math.round(Number(event.target.value)*3600)})}/><em>{ko?"시간":"h"}</em></label><label className="unit-input"><span className="visually-hidden">{ko?"토큰 한도":"Token limit"}</span><input type="number" min={1} step={1000} value={limit.tokenLimit} onChange={event=>updateLimit(index,{tokenLimit:Number(event.target.value)})}/><em>{ko?"토큰":"tokens"}</em></label><SelectMenu label={ko?"계산 대상":"Counts"} value={limit.tokenScope} options={[{value:"input",label:ko?"입력":"Input"},{value:"output",label:ko?"출력":"Output"},{value:"both",label:ko?"입력 + 출력":"Input + output"}]} onChange={value=>updateLimit(index,{tokenScope:value as typeof limit.tokenScope})}/><button className="plan-limit-remove" title={ko?"한도 삭제":"Remove limit"} aria-label={ko?"한도 삭제":"Remove limit"} onClick={()=>setDraft(current=>({...current,tokenLimits:current.tokenLimits.filter((_,i)=>i!==index)}))}><Trash2 size={16}/></button></div>)}</div>:<p className="audit-empty">{ko?"토큰 한도가 없어 이 플랜은 사용량 제한 없이 동작합니다.":"No token limits: this plan is unmetered."}</p>}
        </section>
        {notice&&<p className="settings-notice" role="status">{notice}</p>}
        <div className="plan-editor-actions">{draft.id&&<button className="danger-button" onClick={()=>void remove()}><Trash2 size={15}/>{ko?"플랜 삭제":"Delete plan"}</button>}<button className="save-button" disabled={!draft.name.trim()} onClick={()=>void save()}><Save size={15}/>{draft.id?(ko?"플랜 저장":"Save plan"):(ko?"플랜 만들기":"Create plan")}</button></div>
      </div>
    </div>
    <section className="plan-admin-block"><SectionTitle icon={<Users size={19}/>} title={ko?"사용자별 플랜":"Plans by user"} description={ko?"계정 검색, 플랜 필터와 정렬, 일괄 변경은 별도 창에서 진행합니다.":"Search, filter, sort, and bulk-change account plans in a dedicated window."}/><button className="user-manager-launch" onClick={()=>setUsersOpen(true)}><Users size={17}/><span>{ko?"사용자별 플랜 관리 열기":"Open plan assignments"}</span><ChevronRight size={17}/></button></section>
    <form className="plan-admin-block reset-credit-form" onSubmit={grant}><SectionTitle icon={<TicketCheck size={19}/>} title={ko?"리셋권 지급":"Grant reset credit"} description={ko?"플랜 전체 또는 선택한 사용자에게 시간 범위와 만료일이 있는 리셋권을 지급합니다.":"Grant a whole plan or selected users a reset credit with a time range and expiry."}/>
      <div className="option-cards" role="radiogroup" aria-label={ko?"지급 대상":"Recipients"}>{([["plan",<Layers key="i" size={18}/>,ko?"플랜":"Plan",ko?"플랜을 쓰는 모든 사용자가 받습니다.":"Everyone on the plan receives it."],["user",<UserPlus key="i" size={18}/>,ko?"사용자":"Users",ko?"검색해서 고른 사용자만 받습니다.":"Only the users you pick receive it."]] as const).map(([id,icon,title,description])=><button key={id} type="button" role="radio" aria-checked={creditMode===id} className={creditMode===id?"active":""} onClick={()=>setCreditMode(id)}><span className="option-card-icon">{icon}</span><div><strong>{title}</strong><small>{description}</small></div>{creditMode===id&&<Check size={16}/>}</button>)}</div>
      {creditMode==="plan"?<div className="field"><span>{ko?"대상 플랜":"Target plan"}</span><SelectMenu label={ko?"대상 플랜":"Target plan"} value={creditPlan} options={plans.map(plan=>({value:plan.id,label:plan.name,detail:ko?`${plan.userCount||0}명`:`${plan.userCount||0} users`}))} onChange={setCreditPlan}/></div>
        :<div className="field"><span>{ko?"대상 사용자":"Target users"}</span><div className="credit-recipients"><div>{picked.length?<>{picked.slice(0,6).map(user=><span className="recipient-chip" key={user.id} title={`@${user.username}`}>{user.displayName}</span>)}{picked.length>6&&<span className="recipient-chip more">{ko?`외 ${picked.length-6}명`:`+${picked.length-6} more`}</span>}</>:<small>{ko?"선택한 사용자가 없습니다.":"No users selected."}</small>}</div><button type="button" className="subtle-action" onClick={()=>setPickerOpen(true)}><UserPlus size={14}/>{picked.length?(ko?`${picked.length}명 선택됨 · 변경`:`${picked.length} selected · Change`):(ko?"사용자 선택":"Choose users")}</button></div></div>}
      <div className="credit-fields"><label className="field"><span>{ko?"초기화할 최대 구간":"Reset windows up to"}</span><span className="unit-input"><input type="number" min={1} max={8760} value={creditHours} onChange={event=>setCreditHours(Number(event.target.value))}/><em>{ko?"시간":"h"}</em></span></label><label className="field"><span>{ko?"만료일 (서버 시간)":"Expiry (server time)"}</span><input required type="datetime-local" value={creditExpiry} onChange={event=>setCreditExpiry(event.target.value)}/></label><label className="field credit-title"><span>{ko?"제목":"Title"}</span><input required maxLength={120} value={creditTitle} onChange={event=>setCreditTitle(event.target.value)} placeholder={ko?"예: 점검 보상 리셋권":"e.g. Maintenance make-good"}/></label></div>
      {creditNotice&&<p className="settings-notice" role="status">{creditNotice}</p>}
      <div className="plan-editor-actions"><button className="save-button" disabled={!creditReady}><TicketCheck size={15}/>{ko?"리셋권 지급":"Grant credit"}</button></div>
    </form>
    {usersOpen&&<PlanUsersDialog ko={ko} plans={plans} onClose={()=>setUsersOpen(false)} onChanged={()=>void refreshCounts()}/>}
    {pickerOpen&&<UserPickerDialog ko={ko} initial={creditUsers} onClose={()=>setPickerOpen(false)} onConfirm={setCreditUsers}/>}
  </div>;
}
