"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronLeft, ChevronRight, Download, Eye, FilePlus2, FileText, HardDrive, LoaderCircle, Pencil, Search, Upload, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import rehypeKatex from "rehype-katex";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import type { StorageFile } from "@/lib/types";
import { useModalFocus } from "@/lib/use-modal-focus";
import { SelectMenu } from "./select-menu";
import { StorageUsageMeter } from "./storage-usage-meter";

type StorageState={quotaBytes:number;usedBytes:number;files:StorageFile[];total:number;page:number;pageCount:number;pageSize:number;sort:string;query:string};
type UploadProgress={name:string;fileIndex:number;fileCount:number;uploadedBytes:number;totalBytes:number};
const formatBytes=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(2)} GB`:bytes>=1024**2?`${(bytes/1024**2).toFixed(1)} MB`:bytes>=1024?`${(bytes/1024).toFixed(1)} KB`:`${bytes} B`;

async function jsonResponse(response:Response){const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status}).`);return body;}

function StorageCreateDialog({ko,onClose,onCreated}:{ko:boolean;onClose:()=>void;onCreated:()=>void}){
  const ref=useModalFocus(onClose);const[name,setName]=useState("");const[kind,setKind]=useState<"markdown"|"text">("markdown");const[content,setContent]=useState("");const[preview,setPreview]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  const kindOptions=[{value:"markdown",label:"Markdown (.md)"},{value:"text",label:ko?"텍스트 (.txt)":"Text (.txt)"}];
  async function save(event:React.FormEvent){event.preventDefault();if(!name.trim()||busy)return;setBusy(true);setNotice("");try{await jsonResponse(await fetch("/api/storage/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),kind,content})}));onCreated();}catch(error){setNotice(error instanceof Error?error.message:(ko?"파일을 생성하지 못했습니다.":"File creation failed."));}finally{setBusy(false);}}
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer storage-create-layer" role="dialog" aria-modal="true" aria-label={ko?"새 파일 만들기":"Create a file"}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><form className="harness-dialog storage-create-dialog" onSubmit={save}>
    <header><div><h2>{ko?"새 파일 만들기":"Create a file"}</h2><p>{ko?"Markdown 또는 텍스트 파일을 개인 저장소에 바로 저장합니다.":"Save a Markdown or text file directly to your private storage."}</p></div><button type="button" onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
    <div className="storage-create-fields"><label><span>{ko?"파일 이름":"File name"}</span><input autoFocus value={name} maxLength={240} onChange={event=>setName(event.target.value)} placeholder={kind==="markdown"?"notes.md":"notes.txt"}/></label><label><span>{ko?"파일 형식":"File type"}</span><SelectMenu label={ko?"파일 형식":"File type"} value={kind} options={kindOptions} onChange={value=>{setKind(value as "markdown"|"text");if(value==="text")setPreview(false);}}/></label></div>
    {kind==="markdown"&&<div className="storage-editor-tabs" role="tablist" aria-label={ko?"편집 모드":"Editor mode"}><button type="button" role="tab" aria-selected={!preview} className={!preview?"active":""} onClick={()=>setPreview(false)}><Pencil size={14}/>{ko?"편집":"Write"}</button><button type="button" role="tab" aria-selected={preview} className={preview?"active":""} onClick={()=>setPreview(true)}><Eye size={14}/>{ko?"미리보기":"Preview"}</button></div>}
    {preview&&kind==="markdown"?<div className="markdown-body storage-create-preview" role="tabpanel">{content?<ReactMarkdown remarkPlugins={[remarkGfm,remarkMath]} rehypePlugins={[rehypeKatex]} components={{a:props=><a {...props} target="_blank" rel="noreferrer"/>}}>{content}</ReactMarkdown>:<p className="storage-preview-empty">{ko?"미리볼 내용이 없습니다.":"Nothing to preview yet."}</p>}</div>:<label className="storage-content-field"><span>{ko?"파일 내용":"File content"}</span><textarea value={content} onChange={event=>setContent(event.target.value)} placeholder={kind==="markdown"?(ko?"# 제목부터 작성해 보세요":"# Start with a heading"):(ko?"텍스트를 입력하세요":"Enter text")}/></label>}
    {notice&&<p className="settings-notice" role="alert">{notice}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>{ko?"취소":"Cancel"}</button><button className="save-button" disabled={busy||!name.trim()}>{busy?(ko?"저장 중…":"Saving…"):(ko?"저장소에 저장":"Save to storage")}</button></footer>
  </form></div>,document.body);
}

export function StorageManager({ko,onClose,selectMode=false,maxSelectable=1,onSelect}:{ko:boolean;onClose:()=>void;selectMode?:boolean;maxSelectable?:number;onSelect?:(files:StorageFile[])=>void}) {
  const[storage,setStorage]=useState<StorageState>();const[notice,setNotice]=useState("");const[page,setPage]=useState(1);const[sort,setSort]=useState("created_desc");const[query,setQuery]=useState("");const[search,setSearch]=useState("");const[revision,setRevision]=useState(0);const[createOpen,setCreateOpen]=useState(false);const[uploading,setUploading]=useState(false);const[uploadProgress,setUploadProgress]=useState<UploadProgress>();
  const[selected,setSelected]=useState<Record<string,StorageFile>>({});const fileInput=useRef<HTMLInputElement>(null);const ref=useModalFocus(onClose);
  useEffect(()=>{const timer=window.setTimeout(()=>{setSearch(query.trim());setPage(1);},180);return()=>window.clearTimeout(timer);},[query]);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/storage?page=${page}&pageSize=24&sort=${encodeURIComponent(sort)}&q=${encodeURIComponent(search)}${selectMode?"&attachable=1":""}`,{cache:"no-store",signal:controller.signal}).then(jsonResponse).then(body=>{setStorage(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Storage could not be loaded.");});return()=>controller.abort();},[page,revision,search,selectMode,sort]);
  const sortOptions=[{value:"created_desc",label:ko?"생성일 · 최신순":"Created · newest"},{value:"created_asc",label:ko?"생성일 · 오래된순":"Created · oldest"},{value:"name_asc",label:ko?"파일명 · 오름차순":"Name · A–Z"},{value:"name_desc",label:ko?"파일명 · 내림차순":"Name · Z–A"},{value:"size_desc",label:ko?"크기 · 큰순":"Size · largest"},{value:"size_asc",label:ko?"크기 · 작은순":"Size · smallest"}];
  const selectedFiles=Object.values(selected);function toggle(file:StorageFile){setSelected(current=>{if(current[file.id]){const next={...current};delete next[file.id];return next;}if(Object.keys(current).length>=maxSelectable){setNotice(ko?`최대 ${maxSelectable}개까지 선택할 수 있습니다.`:`You can select up to ${maxSelectable} files.`);return current;}setNotice("");return{...current,[file.id]:file};});}

  async function putChunk(url:string,chunk:Blob){let last:unknown;for(let attempt=0;attempt<3;attempt++)try{const response=await fetch(url,{method:"PUT",headers:{"Content-Type":"application/octet-stream"},body:chunk});await jsonResponse(response);return;}catch(error){last=error;if(attempt<2)await new Promise(resolve=>window.setTimeout(resolve,350*(attempt+1)));}throw last;}
  async function completeUpload(url:string){let last:unknown;for(let attempt=0;attempt<3;attempt++)try{return await jsonResponse(await fetch(url,{method:"POST"}));}catch(error){last=error;if(attempt<2)await new Promise(resolve=>window.setTimeout(resolve,350*(attempt+1)));}throw last;}
  async function uploadFiles(fileList:FileList){
    const files=Array.from(fileList);if(!files.length||uploading)return;setUploading(true);setNotice("");const totalBytes=files.reduce((sum,file)=>sum+file.size,0);let uploadedBytes=0;const failures:string[]=[];
    for(const[fileIndex,file]of files.entries()){let sessionId="";try{setUploadProgress({name:file.name,fileIndex:fileIndex+1,fileCount:files.length,uploadedBytes,totalBytes});const session=await jsonResponse(await fetch("/api/storage/uploads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:file.name,size:file.size,type:file.type})}));sessionId=String(session.id);for(let index=0;index<Number(session.totalChunks);index++){const start=index*Number(session.chunkSize),end=Math.min(file.size,start+Number(session.chunkSize));await putChunk(`/api/storage/uploads/${encodeURIComponent(sessionId)}/chunks/${index}`,file.slice(start,end));uploadedBytes+=end-start;setUploadProgress({name:file.name,fileIndex:fileIndex+1,fileCount:files.length,uploadedBytes,totalBytes});}await completeUpload(`/api/storage/uploads/${encodeURIComponent(sessionId)}/complete`);}catch(error){failures.push(`${file.name}: ${error instanceof Error?error.message:"Upload failed."}`);if(sessionId)await fetch(`/api/storage/uploads/${encodeURIComponent(sessionId)}`,{method:"DELETE"}).catch(()=>undefined);}}
    setUploading(false);setUploadProgress(undefined);if(fileInput.current)fileInput.current.value="";setQuery("");setPage(1);setRevision(value=>value+1);setNotice(failures.length?(ko?`${files.length-failures.length}개 저장, ${failures.length}개 실패 · ${failures.join(" · ")}`:`${files.length-failures.length} saved, ${failures.length} failed · ${failures.join(" · ")}`):(ko?`${files.length}개 파일을 저장했습니다.`:`Saved ${files.length} file(s).`));
  }
  const progressPercent=uploadProgress?.totalBytes?Math.min(100,uploadProgress.uploadedBytes/uploadProgress.totalBytes*100):uploading?0:100;
  function created(){setCreateOpen(false);setQuery("");setPage(1);setRevision(value=>value+1);setNotice(ko?"파일을 저장했습니다.":"File saved.");}
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer storage-manager-layer" role="dialog" aria-modal="true" aria-label={selectMode?(ko?"저장소에서 파일 불러오기":"Choose files from storage"):(ko?"저장소 관리":"Storage manager")}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><section className="harness-dialog storage-manager-dialog">
    <header><div><h2>{selectMode?(ko?"저장소에서 파일 불러오기":"Choose files from storage"):(ko?"저장소 관리":"Storage manager")}</h2><p>{selectMode?(ko?"개인 저장소의 이미지 또는 PDF를 현재 메시지에 첨부합니다.":"Attach images or PDFs from your private storage to this message."):(ko?"개인 파일을 업로드하거나 만들고, 저장된 파일을 탐색하고 다운로드합니다.":"Upload or create private files, then browse and download them.")}</p></div><button onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
    {storage?<div className="storage-meter"><div className="storage-meter-summary"><HardDrive size={18}/><span><strong>{formatBytes(storage.usedBytes)}</strong> / {formatBytes(storage.quotaBytes)}</span><small>{storage.total} {ko?"개 파일":"files"}</small></div><StorageUsageMeter used={storage.usedBytes} total={storage.quotaBytes} label={ko?"개인 저장소":"Personal storage"} ko={ko}/></div>:<div className="storage-loading"><LoaderCircle className="spin" size={20}/></div>}
    {!selectMode&&<div className="storage-actions"><input ref={fileInput} type="file" multiple hidden onChange={event=>event.target.files&&void uploadFiles(event.target.files)}/><button className="storage-action-button primary" disabled={uploading} onClick={()=>fileInput.current?.click()}><Upload size={16}/>{ko?"파일 업로드":"Upload files"}</button><button className="storage-action-button" disabled={uploading} onClick={()=>setCreateOpen(true)}><FilePlus2 size={16}/>{ko?"새 파일 만들기":"Create file"}</button></div>}
    {uploading&&uploadProgress&&<div className="storage-upload-progress" role="status"><div><span>{uploadProgress.fileIndex} / {uploadProgress.fileCount} · {uploadProgress.name}</span><strong>{progressPercent.toFixed(0)}%</strong></div><i><span style={{width:`${progressPercent}%`}}/></i><small>{ko?"8MB 청크로 안전하게 업로드 중입니다. 브라우저를 닫지 마세요.":"Uploading safely in 8 MB chunks. Keep this window open."}</small></div>}
    <div className="storage-browser-toolbar"><label><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={ko?"파일 이름 검색":"Search filenames"}/></label><SelectMenu label={ko?"정렬":"Sort"} value={sort} options={sortOptions} onChange={value=>{setSort(value);setPage(1);}}/></div>
    {notice&&<p className="settings-notice" role="status">{notice}</p>}
    <div className={`storage-file-grid ${selectMode?"selecting":""}`}>{storage?.files.map(file=><article key={file.id} className={selected[file.id]?"selected":""}>
      {selectMode?<button type="button" className="storage-file-preview" aria-pressed={Boolean(selected[file.id])} onClick={()=>toggle(file)}>{file.mimeType.startsWith("image/")?<img src={file.thumbnailUrl||file.url} alt={file.name} loading="lazy"/>:<FileText size={30}/>}<i>{selected[file.id]&&<Check size={16}/>}</i></button>:<a className="storage-file-preview" href={file.url} target="_blank" rel="noreferrer">{file.mimeType.startsWith("image/")?<img src={file.thumbnailUrl||file.url} alt={file.name} loading="lazy"/>:<FileText size={30}/>}</a>}
      <div><strong title={file.name}>{file.name}</strong><small>{formatBytes(file.size)} · {new Date(file.createdAt).toLocaleString(ko?"ko-KR":"en-US")}</small>{file.referenceCount>0&&<em>{ko?`채팅 ${file.referenceCount}곳에서 사용 중`:`Used in ${file.referenceCount} chat message(s)`}</em>}</div>
      {selectMode?<button className="storage-select-file" type="button" onClick={()=>toggle(file)}>{selected[file.id]?(ko?"선택 해제":"Deselect"):(ko?"선택":"Select")}</button>:<span><a href={`${file.url}?download=1`} aria-label={`${ko?"다운로드":"Download"}: ${file.name}`}><Download size={15}/></a></span>}
    </article>)}{storage&&!storage.files.length&&<p className="storage-empty">{search?(ko?"검색 결과가 없습니다.":"No matching files."):(ko?"저장된 파일이 없습니다.":"No stored files.")}</p>}</div>
    {storage&&<nav className="audit-pager"><button disabled={storage.page<=1} onClick={()=>setPage(storage.page-1)}><ChevronLeft size={16}/></button><span>{storage.page} / {storage.pageCount}<small>{ko?`총 ${storage.total}개`:`${storage.total} total`}</small></span><button disabled={storage.page>=storage.pageCount} onClick={()=>setPage(storage.page+1)}><ChevronRight size={16}/></button></nav>}
    {selectMode&&<footer className="storage-picker-footer"><small>{ko?`${selectedFiles.length}개 선택됨`:`${selectedFiles.length} selected`}</small><button className="save-button" disabled={!selectedFiles.length} onClick={()=>onSelect?.(selectedFiles)}>{ko?"선택한 파일 첨부":"Attach selected files"}</button></footer>}
  </section>{createOpen&&<StorageCreateDialog ko={ko} onClose={()=>setCreateOpen(false)} onCreated={created}/>}</div>,document.body);
}
