"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronLeft, ChevronRight, Download, Eye, FilePlus2, FileText, HardDrive, LoaderCircle, Pencil, Search, Trash2, Upload, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import rehypeKatex from "rehype-katex";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import type { ConversationSummary, StorageFile } from "@/lib/types";
import { useModalFocus } from "@/lib/use-modal-focus";
import { SelectMenu } from "./select-menu";
import { StorageUsageMeter } from "./storage-usage-meter";
import { useMessageDialog } from "./message-dialog";

type StorageState={quotaBytes:number;usedBytes:number;files:StorageFile[];total:number;page:number;pageCount:number;pageSize:number;sort:string;query:string};
type UploadProgress={name:string;fileIndex:number;fileCount:number;uploadedBytes:number;totalBytes:number};
const formatBytes=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(2)} GB`:bytes>=1024**2?`${(bytes/1024**2).toFixed(1)} MB`:bytes>=1024?`${(bytes/1024).toFixed(1)} KB`:`${bytes} B`;

async function jsonResponse(response:Response){let body;try{body=await response.json();}catch(error){if(response.ok)throw error;body={};}if(!response.ok)throw new Error(body.error||`Request failed (${response.status}).`);return body;}

function StorageCreateDialog({ko,onClose,onCreated}:{ko:boolean;onClose:()=>void;onCreated:()=>void}){
  const ref=useModalFocus(onClose);const[name,setName]=useState("");const[kind,setKind]=useState<"markdown"|"text">("markdown");const[content,setContent]=useState("");const[preview,setPreview]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  const kindOptions=[{value:"markdown",label:"Markdown (.md)"},{value:"text",label:ko?"텍스트 (.txt)":"Text (.txt)"}];
  async function save(event:React.FormEvent){event.preventDefault();if(!name.trim()||busy)return;setBusy(true);setNotice("");try{await jsonResponse(await fetch("/api/storage/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),kind,content})}));onCreated();}catch(error){setNotice(error instanceof Error?error.message:(ko?"파일을 생성하지 못했습니다.":"File creation failed."));}finally{setBusy(false);}}
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer storage-create-layer" role="dialog" aria-modal="true" aria-label={ko?"새 파일 만들기":"Create a file"}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><form className="harness-dialog storage-create-dialog" onSubmit={save}>
    <header><div><h2>{ko?"새 파일 만들기":"Create a file"}</h2><p>{ko?"Markdown 또는 텍스트 파일을 개인 저장소에 바로 저장합니다.":"Save a Markdown or text file directly to your private storage."}</p></div><button type="button" onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
    <div className="storage-create-fields"><label><span>{ko?"파일 이름":"File name"}</span><input autoFocus value={name} maxLength={240} onChange={event=>setName(event.target.value)} placeholder={kind==="markdown"?"notes.md":"notes.txt"}/></label><label><span>{ko?"파일 형식":"File type"}</span><SelectMenu label={ko?"파일 형식":"File type"} value={kind} options={kindOptions} onChange={value=>{setKind(value as "markdown"|"text");if(value==="text")setPreview(false);}}/></label></div>
    {kind==="markdown"&&<div className="storage-editor-tabs" role="tablist" aria-label={ko?"편집 모드":"Editor mode"}><button type="button" role="tab" aria-selected={!preview} className={!preview?"active":""} onClick={()=>setPreview(false)}><Pencil size={14}/>{ko?"편집":"Write"}</button><button type="button" role="tab" aria-selected={preview} className={preview?"active":""} onClick={()=>setPreview(true)}><Eye size={14}/>{ko?"미리보기":"Preview"}</button></div>}
    {preview&&kind==="markdown"?<div className="markdown-body storage-create-preview" role="tabpanel">{content?<ReactMarkdown remarkPlugins={[remarkGfm,remarkMath]} rehypePlugins={[rehypeKatex]} components={{a:props=><a {...props} target="_blank" rel="noreferrer"/>}}>{content}</ReactMarkdown>:<p className="storage-preview-empty">{ko?"미리볼 내용이 없습니다.":"Nothing to preview yet."}</p>}</div>:<label className="storage-content-field"><span>{ko?"파일 내용":"File content"}</span><textarea value={content} onChange={event=>setContent(event.target.value)} placeholder={kind==="markdown"?(ko?"# 제목부터 작성해 보세요":"# Start with a heading"):(ko?"텍스트를 입력하세요":"Enter text")}/></label>}
    {notice&&<p className="settings-notice" role="alert">{notice}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>{ko?"취소":"Cancel"}</button><button className="save-button" disabled={busy||!name.trim()}>{busy?(ko?"저장 중…":"Saving…"):(ko?"저장소에 저장":"Save to storage")}</button></footer>
  </form></div>,document.body);
}

function FileReferencesDialog({ko,file,onClose,onOpenConversation,onConversationsChanged,onFileDeleted}:{ko:boolean;file:StorageFile;onClose:()=>void;onOpenConversation?:(id:string)=>void;onConversationsChanged:()=>void;onFileDeleted:()=>void}){
  const ref=useModalFocus(onClose);const[items,setItems]=useState<ConversationSummary[]>([]);const[selected,setSelected]=useState<Record<string,boolean>>({});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  const{dialog:messageDialog,confirm:askConfirm}=useMessageDialog(ko);
  async function load(){setLoading(true);try{const body=await jsonResponse(await fetch(`/api/storage/${encodeURIComponent(file.id)}/references`,{cache:"no-store"}));setItems(body.conversations||[]);setSelected(current=>Object.fromEntries(Object.entries(current).filter(([id])=>(body.conversations||[]).some((item:ConversationSummary)=>item.id===id))));}catch(error){setNotice(error instanceof Error?error.message:"Unable to load conversations.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[file.id]);
  function toggle(id:string){setSelected(current=>({...current,[id]:!current[id]}));}
  async function deleteSelected(){const ids=items.filter(item=>selected[item.id]).map(item=>item.id);if(!ids.length||busy)return;if(!await askConfirm({tone:"warning",title:ko?"채팅 삭제":"Delete chats",message:ko?`선택한 채팅 ${ids.length}개를 삭제할까요?`:`Delete ${ids.length} selected chat(s)?`,confirmLabel:ko?"삭제":"Delete"}))return;setBusy(true);setNotice("");try{await jsonResponse(await fetch("/api/conversations",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})}));onConversationsChanged();await load();setNotice(ko?`${ids.length}개 채팅을 삭제했습니다.`:`Deleted ${ids.length} chat(s).`);}catch(error){setNotice(error instanceof Error?error.message:"Unable to delete conversations.");}finally{setBusy(false);}}
  async function deleteAllAndFile(){if(busy)return;if(!await askConfirm({tone:"danger",title:ko?"채팅과 파일 삭제":"Delete chats and file",message:ko?`연관된 채팅 ${items.length}개와 “${file.name}” 파일을 함께 삭제할까요?`:`Delete all ${items.length} related chat(s) and “${file.name}”?`,detail:ko?"파일과 연관 채팅이 함께 삭제됩니다.":"The file and every related chat are removed together.",confirmLabel:ko?"모두 삭제":"Delete all"}))return;setBusy(true);setNotice("");try{await jsonResponse(await fetch("/api/storage",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:[file.id],conversationIds:items.map(item=>item.id),deleteReferencedConversations:true})}));onConversationsChanged();onFileDeleted();}catch(error){setNotice(error instanceof Error?error.message:"Unable to delete related chats and file.");setBusy(false);}}
  const selectedCount=items.filter(item=>selected[item.id]).length;
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer file-references-layer" role="dialog" aria-modal="true" aria-label={ko?"파일을 사용하는 채팅":"Chats using this file"}><button className="settings-backdrop" tabIndex={-1} onClick={onClose}/><section className="harness-dialog file-references-dialog"><header><div><h2>{ko?"파일을 사용하는 채팅":"Chats using this file"}</h2><p><strong>{file.name}</strong> · {ko?`${items.length}개 채팅에서 사용 중`:`Used in ${items.length} chat(s)`}</p></div><button onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
    {loading?<div className="storage-loading"><LoaderCircle className="spin" size={20}/></div>:<div className="file-reference-list">{items.map(item=><article key={item.id}><button className="file-reference-open" onClick={()=>onOpenConversation?.(item.id)}><span><strong>{item.title}</strong><small>{new Date(item.updatedAt).toLocaleString(ko?"ko-KR":"en-US")} · {ko?`${item.branchCount}개 분기`:`${item.branchCount} branch(es)`}</small></span></button><button className={`circle-check ${selected[item.id]?"selected":""}`} aria-label={`${selected[item.id]?(ko?"선택 해제":"Deselect"):(ko?"선택":"Select")}: ${item.title}`} aria-pressed={Boolean(selected[item.id])} onClick={()=>toggle(item.id)}>{selected[item.id]&&<Check size={16}/>}</button></article>)}{!items.length&&<p className="storage-empty">{ko?"활성 채팅에서 더 이상 사용하지 않습니다.":"No active chat uses this file anymore."}</p>}</div>}
    {messageDialog}{notice&&<p className="settings-notice" role="status">{notice}</p>}<footer><button className="secondary-button" onClick={onClose}>{ko?"닫기":"Close"}</button><button className="danger-action compact" disabled={!selectedCount||busy} onClick={()=>void deleteSelected()}>{busy?<LoaderCircle className="spin" size={15}/>:<Trash2 size={15}/>} {ko?`선택 채팅 삭제 (${selectedCount})`:`Delete selected (${selectedCount})`}</button><button className="danger-action compact filled" disabled={loading||busy} onClick={()=>void deleteAllAndFile()}>{busy?<LoaderCircle className="spin" size={15}/>:<Trash2 size={15}/>} {ko?"연관 채팅 전체 및 파일 삭제":"Delete all chats and file"}</button></footer>
  </section></div>,document.body);
}

export function StorageManager({ko,onClose,selectMode=false,maxSelectable=1,onSelect,onOpenConversation,onConversationsChanged}:{ko:boolean;onClose:()=>void;selectMode?:boolean;maxSelectable?:number;onSelect?:(files:StorageFile[])=>void;onOpenConversation?:(id:string)=>void;onConversationsChanged?:()=>void}) {
  const[storage,setStorage]=useState<StorageState>();const[notice,setNotice]=useState("");const[page,setPage]=useState(1);const[sort,setSort]=useState("created_desc");const[query,setQuery]=useState("");const[search,setSearch]=useState("");const[revision,setRevision]=useState(0);const[createOpen,setCreateOpen]=useState(false);const[uploading,setUploading]=useState(false);const[uploadProgress,setUploadProgress]=useState<UploadProgress>();
  const[selected,setSelected]=useState<Record<string,StorageFile>>({});const[deleteMode,setDeleteMode]=useState(false);const[deleting,setDeleting]=useState(false);const[referenceFile,setReferenceFile]=useState<StorageFile>();const[rowCount,setRowCount]=useState(3);const fileInput=useRef<HTMLInputElement>(null);const ref=useModalFocus(onClose);const pageSize=rowCount*2;
  useEffect(()=>{const timer=window.setTimeout(()=>{setSearch(query.trim());setPage(1);},180);return()=>window.clearTimeout(timer);},[query]);
  useEffect(()=>{const resize=()=>{const compact=window.innerWidth<=620;setRowCount(Math.max(3,Math.min(7,Math.floor((window.innerHeight-(compact?520:410))/(compact?78:86)))));};resize();window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize);},[]);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/storage?page=${page}&pageSize=${pageSize}&sort=${encodeURIComponent(sort)}&q=${encodeURIComponent(search)}${selectMode?"&attachable=1":""}`,{cache:"no-store",signal:controller.signal}).then(jsonResponse).then(body=>{setStorage(body);if(body.page!==page)setPage(body.page);}).catch(error=>{if(error?.name!=="AbortError")setNotice(error instanceof Error?error.message:"Storage could not be loaded.");});return()=>controller.abort();},[page,pageSize,revision,search,selectMode,sort]);
  const sortOptions=[{value:"created_desc",label:ko?"생성일 · 최신순":"Created · newest"},{value:"created_asc",label:ko?"생성일 · 오래된순":"Created · oldest"},{value:"name_asc",label:ko?"파일명 · 오름차순":"Name · A–Z"},{value:"name_desc",label:ko?"파일명 · 내림차순":"Name · Z–A"},{value:"size_desc",label:ko?"크기 · 큰순":"Size · largest"},{value:"size_asc",label:ko?"크기 · 작은순":"Size · smallest"}];
  const selectedFiles=Object.values(selected);function toggle(file:StorageFile){setSelected(current=>{if(current[file.id]){const next={...current};delete next[file.id];return next;}const limit=selectMode?maxSelectable:100;if(Object.keys(current).length>=limit){setNotice(ko?`최대 ${limit}개까지 선택할 수 있습니다.`:`You can select up to ${limit} files.`);return current;}setNotice("");return{...current,[file.id]:file};});}
  async function trash(files:StorageFile[]){if(!files.length||deleting)return;const referenced=files.find(file=>file.referenceCount>0);if(referenced){setReferenceFile(referenced);setNotice(ko?"사용 중인 파일은 연관 채팅을 먼저 확인해 주세요.":"Review related chats before deleting an in-use file.");return;}setDeleting(true);setNotice("");try{const body=await jsonResponse(await fetch("/api/storage",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:files.map(file=>file.id),page,pageSize,sort,query:search})}));setStorage(body);if(body.page!==page)setPage(body.page);setSelected(current=>{const next={...current};for(const file of files)delete next[file.id];return next;});if(files.length>1)setDeleteMode(false);setNotice(ko?`${files.length}개 파일을 삭제했습니다.`:`Deleted ${files.length} file(s).`);}catch(error){setNotice(error instanceof Error?error.message:(ko?"파일을 삭제하지 못했습니다.":"Files could not be deleted."));}finally{setDeleting(false);}}

  async function putChunk(url:string,chunk:Blob){let last:unknown;for(let attempt=0;attempt<3;attempt++)try{const response=await fetch(url,{method:"PUT",headers:{"Content-Type":"application/octet-stream"},body:chunk});await jsonResponse(response);return;}catch(error){last=error;if(attempt<2)await new Promise(resolve=>window.setTimeout(resolve,350*(attempt+1)));}throw last;}
  async function completeUpload(url:string){let last:unknown;for(let attempt=0;attempt<3;attempt++)try{return await jsonResponse(await fetch(url,{method:"POST"}));}catch(error){last=error;if(attempt<2)await new Promise(resolve=>window.setTimeout(resolve,350*(attempt+1)));}throw last;}
  async function uploadFiles(fileList:FileList){
    const files=Array.from(fileList);if(!files.length||uploading)return;setUploading(true);setNotice("");const totalBytes=files.reduce((sum,file)=>sum+file.size,0);let uploadedBytes=0;const failures:string[]=[];
    for(const[fileIndex,file]of files.entries()){let sessionId="";try{setUploadProgress({name:file.name,fileIndex:fileIndex+1,fileCount:files.length,uploadedBytes,totalBytes});const session=await jsonResponse(await fetch("/api/storage/uploads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:file.name,size:file.size,type:file.type})}));sessionId=String(session.id);for(let index=0;index<Number(session.totalChunks);index++){const start=index*Number(session.chunkSize),end=Math.min(file.size,start+Number(session.chunkSize));await putChunk(`/api/storage/uploads/${encodeURIComponent(sessionId)}/chunks/${index}`,file.slice(start,end));uploadedBytes+=end-start;setUploadProgress({name:file.name,fileIndex:fileIndex+1,fileCount:files.length,uploadedBytes,totalBytes});}await completeUpload(`/api/storage/uploads/${encodeURIComponent(sessionId)}/complete`);}catch(error){failures.push(`${file.name}: ${error instanceof Error?error.message:"Upload failed."}`);if(sessionId)await fetch(`/api/storage/uploads/${encodeURIComponent(sessionId)}`,{method:"DELETE"}).catch(()=>undefined);}}
    setUploading(false);setUploadProgress(undefined);if(fileInput.current)fileInput.current.value="";setQuery("");setPage(1);setRevision(value=>value+1);setNotice(failures.length?(ko?`${files.length-failures.length}개 저장, ${failures.length}개 실패 · ${failures.join(" · ")}`:`${files.length-failures.length} saved, ${failures.length} failed · ${failures.join(" · ")}`):(ko?`${files.length}개 파일을 저장했습니다.`:`Saved ${files.length} file(s).`));
  }
  const progressPercent=uploadProgress?.totalBytes?Math.min(100,uploadProgress.uploadedBytes/uploadProgress.totalBytes*100):uploading?0:100;
  function created(){setCreateOpen(false);setQuery("");setPage(1);setRevision(value=>value+1);setNotice(ko?"파일을 저장했습니다.":"File saved.");}
  return createPortal(<div ref={ref} tabIndex={-1} className="harness-modal-layer storage-manager-layer" role="dialog" aria-modal="true" aria-label={selectMode?(ko?"저장소에서 파일 불러오기":"Choose files from storage"):(ko?"저장소 관리":"Storage manager")}><button className="settings-backdrop" tabIndex={-1} onClick={onClose} aria-label={ko?"닫기":"Close"}/><section className="harness-dialog storage-manager-dialog">
    <header><div><h2>{selectMode?(ko?"저장소에서 파일 불러오기":"Choose files from storage"):(ko?"저장소 관리":"Storage manager")}</h2><p>{selectMode?(ko?"개인 저장소의 이미지 또는 PDF를 현재 메시지에 첨부합니다.":"Attach images or PDFs from your private storage to this message."):(ko?"개인 파일을 업로드하거나 만들고, 저장된 파일을 탐색하고 다운로드합니다.":"Upload or create private files, then browse and download them.")}</p></div><button onClick={onClose} aria-label={ko?"닫기":"Close"}><X size={20}/></button></header>
    {storage?<div className="storage-meter"><div className="storage-meter-summary"><HardDrive size={18}/><span><strong>{formatBytes(storage.usedBytes)}</strong> / {formatBytes(storage.quotaBytes)}</span><small>{storage.total} {ko?"개 파일":"files"}</small></div><StorageUsageMeter used={storage.usedBytes} total={storage.quotaBytes} label={ko?"개인 저장소":"Personal storage"} ko={ko}/></div>:<div className="storage-loading"><LoaderCircle className="spin" size={20}/></div>}
    {!selectMode&&<div className="storage-actions"><input ref={fileInput} type="file" multiple hidden onChange={event=>event.target.files&&void uploadFiles(event.target.files)}/><button className="storage-action-button primary" disabled={uploading} onClick={()=>fileInput.current?.click()}><Upload size={16}/>{ko?"파일 업로드":"Upload files"}</button><button className="storage-action-button" disabled={uploading} onClick={()=>setCreateOpen(true)}><FilePlus2 size={16}/>{ko?"새 파일 만들기":"Create file"}</button><button className={`storage-action-button storage-batch-button ${deleteMode?"active":""}`} disabled={uploading} onClick={()=>{setDeleteMode(value=>!value);setSelected({});setNotice("");}}><Check size={16}/>{deleteMode?(ko?"선택 종료":"Finish selecting"):(ko?"일괄 선택":"Select multiple")}</button></div>}
    {uploading&&uploadProgress&&<div className="storage-upload-progress" role="status"><div><span>{uploadProgress.fileIndex} / {uploadProgress.fileCount} · {uploadProgress.name}</span><strong>{progressPercent.toFixed(0)}%</strong></div><i><span style={{width:`${progressPercent}%`}}/></i><small>{ko?"8MB 청크로 안전하게 업로드 중입니다. 브라우저를 닫지 마세요.":"Uploading safely in 8 MB chunks. Keep this window open."}</small></div>}
    <div className="storage-browser-toolbar"><label><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={ko?"파일 이름 검색":"Search filenames"}/></label><SelectMenu label={ko?"정렬":"Sort"} value={sort} options={sortOptions} onChange={value=>{setSort(value);setPage(1);}}/></div>
    {!selectMode&&deleteMode&&<div className="storage-delete-toolbar" role="status"><span><Check size={15}/><strong>{ko?`${selectedFiles.length}개 선택됨`:`${selectedFiles.length} selected`}</strong><small>{ko?"파일을 눌러 선택을 변경하세요.":"Select or deselect files with a click."}</small></span><button type="button" onClick={()=>{setSelected({});setDeleteMode(false);}} disabled={deleting}><X size={15}/>{ko?"취소":"Cancel"}</button><button type="button" className="danger" disabled={!selectedFiles.length||deleting} onClick={()=>void trash(selectedFiles)}>{deleting?<LoaderCircle className="spin" size={15}/>:<Trash2 size={15}/>} {ko?"선택 항목 삭제":"Delete selected"}</button></div>}
    {notice&&<p className="settings-notice" role="status">{notice}</p>}
    <div className={`storage-file-grid ${selectMode||deleteMode?"selecting":""}`} style={{"--storage-rows":rowCount} as React.CSSProperties}>{storage?.files.map(file=><article key={file.id} className={selected[file.id]?"selected":""}>
      {selectMode||deleteMode?<button type="button" className="storage-file-preview" aria-pressed={Boolean(selected[file.id])} onClick={()=>toggle(file)}>{file.mimeType.startsWith("image/")?<img src={file.thumbnailUrl||file.url} alt={file.name} loading="lazy"/>:<FileText size={30}/>}</button>:<a className="storage-file-preview" href={file.url} target="_blank" rel="noreferrer">{file.mimeType.startsWith("image/")?<img src={file.thumbnailUrl||file.url} alt={file.name} loading="lazy"/>:<FileText size={30}/>}</a>}
      <div><strong title={file.name}>{file.name}</strong><small>{formatBytes(file.size)} · {new Date(file.createdAt).toLocaleString(ko?"ko-KR":"en-US")}</small>{file.referenceCount>0&&<em>{ko?`채팅 ${file.referenceCount}곳에서 사용 중`:`Used in ${file.referenceCount} chat message(s)`}</em>}</div>
      {selectMode||deleteMode?<span className="storage-selection-action"><button className={`circle-check ${selected[file.id]?"selected":""}`} type="button" aria-pressed={Boolean(selected[file.id])} aria-label={`${selected[file.id]?(ko?"선택 해제":"Deselect"):(ko?"선택":"Select")}: ${file.name}`} onClick={()=>toggle(file)}>{selected[file.id]&&<Check size={16}/>}</button></span>:<span><a href={`${file.url}?download=1`} aria-label={`${ko?"다운로드":"Download"}: ${file.name}`}><Download size={15}/></a><button type="button" className="storage-delete-file" disabled={deleting} title={file.referenceCount>0?(ko?"사용 중인 채팅 확인":"Review chats using this file"):(ko?"삭제":"Delete")} aria-label={`${ko?"삭제":"Delete"}: ${file.name}`} onClick={()=>file.referenceCount>0?setReferenceFile(file):void trash([file])}><Trash2 size={15}/></button></span>}
    </article>)}{storage&&!storage.files.length&&<p className="storage-empty">{search?(ko?"검색 결과가 없습니다.":"No matching files."):(ko?"저장된 파일이 없습니다.":"No stored files.")}</p>}</div>
    {storage&&<nav className="audit-pager"><button disabled={storage.page<=1} onClick={()=>setPage(storage.page-1)}><ChevronLeft size={16}/></button><span>{storage.page} / {storage.pageCount}<small>{ko?`총 ${storage.total}개`:`${storage.total} total`}</small></span><button disabled={storage.page>=storage.pageCount} onClick={()=>setPage(storage.page+1)}><ChevronRight size={16}/></button></nav>}
    {selectMode&&<footer className="storage-picker-footer"><small>{ko?`${selectedFiles.length}개 선택됨`:`${selectedFiles.length} selected`}</small><button className="save-button" disabled={!selectedFiles.length} onClick={()=>onSelect?.(selectedFiles)}>{ko?"선택한 파일 첨부":"Attach selected files"}</button></footer>}
  </section>{createOpen&&<StorageCreateDialog ko={ko} onClose={()=>setCreateOpen(false)} onCreated={created}/>} {referenceFile&&<FileReferencesDialog ko={ko} file={referenceFile} onOpenConversation={id=>{onClose();onOpenConversation?.(id);}} onConversationsChanged={()=>onConversationsChanged?.()} onFileDeleted={()=>{setReferenceFile(undefined);setRevision(value=>value+1);setSelected(current=>{const next={...current};delete next[referenceFile.id];return next;});}} onClose={()=>{setReferenceFile(undefined);setRevision(value=>value+1);}}/>}</div>,document.body);
}
