import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { accessSync, chmodSync, constants, existsSync, lstatSync, mkdirSync, readFileSync, renameSync, rmSync, copyFileSync, readdirSync } from "node:fs";
import { mkdtemp, open, rm, writeFile, mkdir, copyFile, statfs } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { path7za } from "7zip-bin";
import { z } from "zod";
import { AuthError, type AuthUser, verifyPassword, logAdminAudit, removeOwnedConfigEntries } from "./auth";
import { encryptBackup, decryptBackup, validateCredentials, type BackupCredentials } from "./backup-crypto";
import { dataDir, db } from "./database";
import { readConfig, writeConfig } from "./config";
import { applyModelSettingsImage, modelSettingsImage, type ModelSettingsReport } from "./model-settings-backup";
import { discardChatJobs } from "./chat-disposal";

export const BACKUP_IMAGE_VERSION=1;
export type BackupScope="personal"|"global"|"accounts"|"user";
type RestoreMode="merge"|"replace";
type ImageData={profile?:Record<string,unknown>;tables?:Record<string,Array<Record<string,unknown>>>;config?:Record<string,unknown>;modelSettings?:unknown};
type Manifest={format:"neuralnetui-backup";imageVersion:number;appVersion:string;scope:BackupScope;createdAt:string;owner?:{id:string;username:string};skippedUploads?:string[];dataFile:"data.json"};
const manifestSchema=z.object({format:z.literal("neuralnetui-backup"),imageVersion:z.number().int().nonnegative(),appVersion:z.string(),scope:z.enum(["personal","global","accounts","user"]),createdAt:z.string(),owner:z.object({id:z.string(),username:z.string()}).optional(),skippedUploads:z.array(z.string()).optional(),dataFile:z.literal("data.json")});
const uploadsDir=path.join(dataDir,"uploads");
const personalTables=["conversations","branches","messages","branch_messages","uploads","artifact_storage_links","message_attachments","context_summaries","mcp_connections","mcp_tool_policies"] as const;
const accountColumns=["id","username","display_name","password_hash","role","preferences","storage_quota_bytes","trash_quota_bytes","storage_quota_uses_default","trash_quota_uses_default","audit_enabled","plan_id","created_at","updated_at"];
const tableColumns:Record<string,string[]>={
  conversations:["id","title","model_id","reasoning_preset_id","active_branch_id","created_at","updated_at","user_id","title_managed","temporary","deleted_at"],
  branches:["id","conversation_id","name","parent_branch_id","forked_from_message_id","position","created_at","updated_at"],
  messages:["id","conversation_id","revision_group_id","role","content","reasoning","reasoning_duration_seconds","created_at","input_tokens","output_tokens","reasoning_tokens","total_tokens","completion_duration_seconds","time_to_first_token_seconds","tool_events","context_tokens","steps"],
  branch_messages:["branch_id","message_id","position"],uploads:["id","name","mime_type","size","width","height","created_at","user_id","retained","deleted_at"],artifact_storage_links:["user_id","conversation_id","artifact_key","upload_id","created_at","updated_at"],message_attachments:["message_id","upload_id","position"],context_summaries:["branch_id","fingerprint","covered_count","summary"],
  users:accountColumns,plans:["id","name","storage_quota_bytes","trash_quota_bytes","served_model_ids","model_weights","mcp_enabled","max_mcp_connections","created_at","updated_at"],plan_token_limits:["id","plan_id","duration_seconds","token_limit","token_scope","position"],reset_credits:["id","target_type","target_id","max_window_seconds","expires_at","title","created_at","created_by"],
  mcp_connections:["id","user_id","name","description","url","auth_type","credential","enabled","created_at","updated_at"],
  mcp_tool_policies:["connection_id","tool_name","policy","updated_at"],
};
function sanitizedRows(table:string,value:unknown){if(!Array.isArray(value))throw new AuthError(`백업 이미지에 ${table} 데이터가 없습니다.`,400);const allowed=tableColumns[table];if(!allowed)throw new AuthError("지원하지 않는 백업 데이터입니다.",400);return value.map((candidate,index)=>{if(!candidate||typeof candidate!=="object"||Array.isArray(candidate))throw new AuthError(`${table}의 ${index+1}번째 항목이 올바르지 않습니다.`,400);const row:Record<string,unknown>={};for(const column of allowed)if(Object.hasOwn(candidate,column))row[column]=(candidate as Record<string,unknown>)[column];return row;});}

// npm tarballs and Next's standalone tracing can both lose the executable bit of the bundled
// 7-Zip binary, which surfaces as spawn EACCES on Linux. Restore it once, or run a private copy
// when the install directory is read-only.
let resolved7z:string|undefined;
export function bundled7z(){if(resolved7z&&existsSync(/* turbopackIgnore: true */ resolved7z))return resolved7z;const relative=process.platform==="win32"?path.join("win",process.arch,"7za.exe"):process.platform==="darwin"?path.join("mac",process.arch,"7za"):path.join("linux",process.arch,"7za");const candidate=path.join(/* turbopackIgnore: true */ process.cwd(),"node_modules","7zip-bin",relative);let binary=existsSync(/* turbopackIgnore: true */ candidate)?candidate:path7za;if(process.platform!=="win32")binary=ensureExecutable(binary);resolved7z=binary;return binary;}
function ensureExecutable(binary:string){const runnable=(file:string)=>{try{accessSync(file,constants.X_OK);return true;}catch{return false;}};if(runnable(binary))return binary;try{chmodSync(binary,0o755);if(runnable(binary))return binary;}catch{}const copy=path.join(os.tmpdir(),`neuralnetui-7za-${process.arch}-${process.getuid?.()??"user"}`);if(!runnable(copy)||lstatSync(copy).size!==lstatSync(binary).size){const staged=`${copy}.${randomUUID()}`;copyFileSync(binary,staged);chmodSync(staged,0o755);renameSync(staged,copy);}return copy;}
function run7zCapture(args:string[],cwd?:string){return new Promise<string>((resolve,reject)=>{const child=spawn(/* turbopackIgnore: true */ bundled7z(),args,{cwd,windowsHide:true,stdio:["ignore","pipe","pipe"]});let output="",error="";child.stdout.on("data",chunk=>{output+=chunk;if(output.length>64*1024**2){child.kill();reject(new AuthError("백업 이미지 항목 목록이 너무 큽니다.",413));}});child.stderr.on("data",chunk=>{error=(error+chunk).slice(-8000);});child.once("error",reject);child.once("exit",code=>code===0?resolve(output):reject(new Error(`7z failed with code ${code}: ${error}`)));});}
async function run7z(args:string[],cwd?:string){await run7zCapture(args,cwd);}
async function validateArchiveListing(archivePath:string,extractRoot:string){const listing=await run7zCapture(["l","-slt",archivePath]);const details=listing.slice(Math.max(0,listing.indexOf("----------")));if(/^(?:Symbolic Link|Hard Link) =|^Attributes = .*l[rwx-]{9}/m.test(details))throw new AuthError("백업 이미지에 링크를 사용할 수 없습니다.",400);const paths=[...details.matchAll(/^Path = (.+)$/gm)].map(match=>match[1].trim());if(!paths.length||paths.length>2_000_000)throw new AuthError("백업 이미지의 항목 수가 올바르지 않습니다.",413);for(const entry of paths){if(!/^(manifest\.json|data\.json|files(?:[\\/][a-zA-Z0-9_.-]+)?)$/.test(entry)||entry.includes(":")||entry.startsWith("/")||entry.startsWith("\\")||entry.split(/[\\/]/).some(part=>part===".."))throw new AuthError("백업 이미지에 안전하지 않은 경로가 있습니다.",400);}const unpacked=[...details.matchAll(/^Size = (\d+)$/gm)].reduce((sum,match)=>sum+Number(match[1]),0);const disk=await statfs(extractRoot);const available=Number(disk.bavail)*Number(disk.bsize);if(!Number.isSafeInteger(unpacked)||unpacked>10*1024**4||unpacked>available*.8)throw new AuthError("백업 이미지의 압축 해제 크기가 시스템 한도를 초과합니다.",413);}
function all(sql:string,...args:unknown[]){return db.prepare(sql).all(...args) as Array<Record<string,unknown>>;}
function placeholders(values:unknown[]){return values.map(()=>"?").join(",");}
function userData(userId:string):ImageData{
  const conversations=all("SELECT * FROM conversations WHERE user_id=?",userId);
  const conversationIds=conversations.map(row=>row.id);
  const branches=conversationIds.length?all(`SELECT * FROM branches WHERE conversation_id IN (${placeholders(conversationIds)})`,...conversationIds):[];
  const branchIds=branches.map(row=>row.id);
  const messages=conversationIds.length?all(`SELECT * FROM messages WHERE conversation_id IN (${placeholders(conversationIds)})`,...conversationIds):[];
  const messageIds=messages.map(row=>row.id);
  const uploads=all("SELECT * FROM uploads WHERE user_id=?",userId);
  const user=db.prepare("SELECT display_name,preferences FROM users WHERE id=?").get(userId) as {display_name:string;preferences:string};
  return {profile:{displayName:user.display_name,preferences:user.preferences},tables:{
    conversations,branches,messages,
    branch_messages:branchIds.length?all(`SELECT * FROM branch_messages WHERE branch_id IN (${placeholders(branchIds)})`,...branchIds):[],
    uploads,
    artifact_storage_links:all("SELECT * FROM artifact_storage_links WHERE user_id=?",userId),
    message_attachments:messageIds.length?all(`SELECT * FROM message_attachments WHERE message_id IN (${placeholders(messageIds)})`,...messageIds):[],
    context_summaries:branchIds.length?all(`SELECT * FROM context_summaries WHERE branch_id IN (${placeholders(branchIds)})`,...branchIds):[],
    mcp_connections:all("SELECT * FROM mcp_connections WHERE user_id=?",userId),
    mcp_tool_policies:all("SELECT p.* FROM mcp_tool_policies p JOIN mcp_connections m ON m.id=p.connection_id WHERE m.user_id=?",userId),
  }};
}
function safeFileNames(ids:string[],directory=uploadsDir){const allowed=new Set(ids);return existsSync(directory)?readdirSync(directory).filter(name=>{const id=name.split(".")[0];return allowed.has(id)&&/^[a-zA-Z0-9_-]+\.[a-zA-Z0-9_.-]+$/.test(name)&&!/\.(tmp|restore|backup)$/.test(name);}):[];}
function isAdminRole(role:unknown){return role==="admin"||role==="superadmin";}
function readPreferences(value:unknown){try{const parsed=JSON.parse(String(value||"{}"));return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{};}}
// The model settings download, stored beside the owner's data so a personal restore brings back their aliases and templates.
async function personalModelSettings(userId:string){const row=db.prepare("SELECT role,preferences FROM users WHERE id=?").get(userId) as {role:string;preferences:string};const preferences=readPreferences(row.preferences),config=await readConfig();const pick=(key:"defaultModelId"|"defaultReasoningPresetId")=>typeof preferences[key]==="string"?preferences[key] as string:config.preferences[key];return modelSettingsImage(config.models,{id:userId,admin:isAdminRole(row.role)},{modelId:pick("defaultModelId"),reasoningPresetId:pick("defaultReasoningPresetId")});}
// Model settings restore on a best-effort basis after the data itself: a model this workspace does not
// serve is skipped instead of failing the restore, and saved defaults that no longer resolve fall back
// to the workspace defaults.
type ModelSettingsOutcome=({status:"restored"}&ModelSettingsReport)|{status:"absent"|"invalid"|"failed"};
async function restorePersonalModelSettings(data:ImageData,userId:string,mode:RestoreMode):Promise<ModelSettingsOutcome>{const role=(db.prepare("SELECT role FROM users WHERE id=?").get(userId) as {role:string}).role;let outcome:ModelSettingsOutcome={status:"absent"};let idMap=new Map<string,string>();let config=await readConfig();if(data.modelSettings!==undefined){try{const result=applyModelSettingsImage(config.models,data.modelSettings,{id:userId,admin:isAdminRole(role)},mode);if(!result)outcome={status:"invalid"};else{config=await writeConfig({...config,models:result.models});idMap=result.idMap;outcome={status:"restored",...result.report};}}catch(error){console.error("Unable to restore backup model settings",error);outcome={status:"failed"};}}
  const usable=config.models.filter(model=>!model.isAlias||!model.ownerId||model.ownerId===userId||model.isPublic===true);const preferences=readPreferences((db.prepare("SELECT preferences FROM users WHERE id=?").get(userId) as {preferences:string}).preferences);const next={...preferences};
  if(typeof next.defaultModelId==="string"){next.defaultModelId=idMap.get(next.defaultModelId)||next.defaultModelId;if(!usable.some(model=>model.id===next.defaultModelId))delete next.defaultModelId;}
  if(typeof next.defaultReasoningPresetId==="string"&&!usable.some(model=>model.reasoningPresets.some(preset=>preset.id===next.defaultReasoningPresetId&&(preset.kind==="builtin"||!preset.ownerId||preset.ownerId===userId))))delete next.defaultReasoningPresetId;
  if(JSON.stringify(next)!==JSON.stringify(preferences))db.prepare("UPDATE users SET preferences=?,updated_at=? WHERE id=?").run(JSON.stringify(next),new Date().toISOString(),userId);
  return outcome;}
// Aliases that must take a private identifier on this workspace keep their conversations pointing at them.
async function renameRestoredAliases(data:ImageData,userId:string,mode:RestoreMode){if(data.modelSettings===undefined)return data;const role=(db.prepare("SELECT role FROM users WHERE id=?").get(userId) as {role:string}).role;const result=applyModelSettingsImage((await readConfig()).models,data.modelSettings,{id:userId,admin:isAdminRole(role)},mode);if(!result?.idMap.size)return data;const conversations=(data.tables?.conversations||[]).map(row=>typeof row.model_id==="string"&&result.idMap.has(row.model_id)?{...row,model_id:result.idMap.get(row.model_id)}:row);return{...data,tables:{...data.tables,conversations}};}
function selectedUser(actor:AuthUser,scope:BackupScope,targetUserId?:string){if(scope==="personal")return actor.id;if(scope==="user"){if(actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);if(!targetUserId||!db.prepare("SELECT 1 FROM users WHERE id=?").get(targetUserId))throw new AuthError("사용자를 찾을 수 없습니다.",404);return targetUserId;}return undefined;}

export async function createBackupImage(actor:AuthUser,scope:BackupScope,appVersion:string,targetUserId?:string,credentials?:BackupCredentials){const userId=selectedUser(actor,scope,targetUserId);if((scope==="global"||scope==="accounts")&&actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);const secret=validateCredentials(credentials);const credentialOwner=db.prepare("SELECT username,password_hash FROM users WHERE id=?").get(userId||actor.id) as {username:string;password_hash:string};if(secret.username!==credentialOwner.username.toLowerCase()||!await verifyPassword(secret.password,credentialOwner.password_hash))throw new AuthError("백업 소유자의 아이디 또는 비밀번호가 일치하지 않습니다.",403);const temp=await mkdtemp(path.join(os.tmpdir(),"neural-backup-"));try{const content=path.join(temp,"content");const archive=path.join(temp,`NeuralNetUI-${scope}-${new Date().toISOString().replace(/[:.]/g,"-")}.7z`);await mkdir(content,{recursive:true});let data:ImageData;let owner:Manifest["owner"];let skippedUploads:string[]=[];
    if(userId){const row=db.prepare("SELECT username FROM users WHERE id=?").get(userId) as {username:string};data={...userData(userId),modelSettings:await personalModelSettings(userId)};owner={id:userId,username:row.username};const files=path.join(content,"files");await mkdir(files,{recursive:true});const tables=data.tables!;const missing=new Set(tables.uploads.map(item=>String(item.id)).filter(id=>!existsSync(path.join(uploadsDir,`${id}.original`))));if(missing.size){tables.uploads=tables.uploads.filter(item=>!missing.has(String(item.id)));tables.message_attachments=tables.message_attachments.filter(item=>!missing.has(String(item.upload_id)));tables.artifact_storage_links=tables.artifact_storage_links.filter(item=>!missing.has(String(item.upload_id)));skippedUploads=[...missing];}const uploadIds=tables.uploads.map(item=>String(item.id));for(const name of safeFileNames(uploadIds))await copyFile(path.join(uploadsDir,name),path.join(files,name));}
    else if(scope==="global"){const value=(db.prepare("SELECT value FROM app_config WHERE id=1").get() as {value:string}|undefined)?.value||"{}";data={config:JSON.parse(value)};}
    else data={tables:{users:all(`SELECT ${accountColumns.join(",")} FROM users`),plans:all("SELECT * FROM plans"),plan_token_limits:all("SELECT * FROM plan_token_limits"),reset_credits:all("SELECT * FROM reset_credits"),mcp_connections:all("SELECT * FROM mcp_connections"),mcp_tool_policies:all("SELECT * FROM mcp_tool_policies")}};
    const manifest:Manifest={format:"neuralnetui-backup",imageVersion:BACKUP_IMAGE_VERSION,appVersion,scope,createdAt:new Date().toISOString(),...(owner?{owner}:{}),...(skippedUploads.length?{skippedUploads}:{}),dataFile:"data.json"};await writeFile(path.join(content,"manifest.json"),JSON.stringify(manifest,null,2),"utf8");await writeFile(path.join(content,"data.json"),JSON.stringify(data),"utf8");await run7z(["a","-t7z","-mx=9","-m0=lzma2","-mmt=on",archive,"."],content);if(scope!=="personal")logAdminAudit(actor.id,userId||actor.id,`backup.${scope}`);const encrypted=archive.replace(/\.7z$/,".nnbak");await encryptBackup(archive,encrypted,secret);await rm(archive);return{path:encrypted,name:path.basename(encrypted),cleanup:()=>rm(temp,{recursive:true,force:true})};
  }catch(error){await rm(temp,{recursive:true,force:true}).catch(()=>undefined);throw error;}}

function migrateImage(version:number,data:ImageData){let current=version;let migrated=data;while(current<BACKUP_IMAGE_VERSION){if(current===0){migrated={...migrated,tables:migrated.tables||{}};current=1;continue;}throw new AuthError(`이미지 버전 ${current}에서 ${current+1}(으)로 승계할 어댑터가 없습니다.`,400);}return migrated;}
function validateExtracted(root:string){const walk=(directory:string)=>{for(const entry of readdirSync(directory,{withFileTypes:true})){const full=path.join(directory,entry.name);const relative=path.relative(root,full);if(relative.startsWith("..")||path.isAbsolute(relative))throw new AuthError("백업 이미지에 안전하지 않은 경로가 있습니다.",400);const stats=lstatSync(full);if(stats.isSymbolicLink())throw new AuthError("백업 이미지에 심볼릭 링크를 사용할 수 없습니다.",400);if(stats.isDirectory())walk(full);}};walk(root);}
function insertRows(table:string,rows:Array<Record<string,unknown>>,mode:"insert"|"replace"="insert"){if(!rows.length)return;const columns=Object.keys(rows[0]);const statement=db.prepare(`${mode==="replace"?"INSERT OR REPLACE":"INSERT"} INTO ${table}(${columns.join(",")}) VALUES (${columns.map(column=>`@${column}`).join(",")})`);for(const row of rows)statement.run(row);}
function upsertRows(table:string,rows:Array<Record<string,unknown>>,conflict:string[]){if(!rows.length)return;const columns=Object.keys(rows[0]),updates=columns.filter(column=>!conflict.includes(column)).map(column=>`${column}=excluded.${column}`).join(",");const statement=db.prepare(`INSERT INTO ${table}(${columns.join(",")}) VALUES (${columns.map(column=>`@${column}`).join(",")}) ON CONFLICT(${conflict.join(",")}) DO UPDATE SET ${updates}`);for(const row of rows)statement.run(row);}
// Stable destination IDs make repeated cross-account imports idempotent without colliding
// with source records. Rewrite graph references and attachment URLs together with filenames.
function remapPersonal(data:ImageData,userId:string,filesDir:string){
  const ids=new Map<string,string>();for(const table of ["conversations","branches","messages","uploads","mcp_connections"])for(const row of data.tables?.[table]||[])if(typeof row.id==="string")ids.set(row.id,createHash("sha256").update(JSON.stringify([userId,row.id])).digest("hex"));
  const rewrite=(value:unknown):unknown=>{if(typeof value==="string"){if(ids.has(value))return ids.get(value);return value.replace(/\/api\/uploads\/([a-zA-Z0-9_-]+)/g,(full,id:string)=>ids.has(id)?`/api/uploads/${ids.get(id)}`:full);}if(Array.isArray(value))return value.map(rewrite);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,rewrite(item)]));return value;};
  for(const name of safeFileNames([...ids.keys()],filesDir)){const split=name.indexOf(".");renameSync(path.join(filesDir,name),path.join(filesDir,`${ids.get(name.slice(0,split))}${name.slice(split)}`));}return rewrite(data) as ImageData;
}
function personalRestore(data:ImageData,userId:string,mode:RestoreMode,filesDir:string){const source=data.tables||{},tables=Object.fromEntries(personalTables.map(table=>[table,sanitizedRows(table,source[table]??(["artifact_storage_links","mcp_connections","mcp_tool_policies"].includes(table)?[]:undefined))])) as Record<(typeof personalTables)[number],Array<Record<string,unknown>>>;const conversations=tables.conversations;const uploads=tables.uploads;for(const row of conversations)row.user_id=userId;for(const row of uploads)row.user_id=userId;for(const row of tables.artifact_storage_links)row.user_id=userId;for(const row of tables.mcp_connections)row.user_id=userId;for(const row of [...conversations,...uploads,...tables.mcp_connections])if(!/^[a-zA-Z0-9_-]{1,200}$/.test(String(row.id||"")))throw new AuthError("백업 이미지에 올바르지 않은 데이터 식별자가 있습니다.",400);const foreignConversation=conversations.find(row=>{const existing=db.prepare("SELECT user_id FROM conversations WHERE id=?").get(row.id) as {user_id:string}|undefined;return existing&&existing.user_id!==userId;});const foreignUpload=uploads.find(row=>{const existing=db.prepare("SELECT user_id FROM uploads WHERE id=?").get(row.id) as {user_id:string}|undefined;return existing&&existing.user_id!==userId;});const foreignMcp=tables.mcp_connections.find(row=>{const existing=db.prepare("SELECT user_id FROM mcp_connections WHERE id=?").get(row.id) as {user_id:string}|undefined;return existing&&existing.user_id!==userId;});if(foreignConversation||foreignUpload||foreignMcp)throw new AuthError("다른 사용자의 데이터와 식별자가 충돌합니다.",409);
  const ownConversations=new Set(conversations.map(row=>row.id)),ownBranches=new Set(tables.branches.map(row=>row.id)),ownMessages=new Set(tables.messages.map(row=>row.id)),ownUploads=new Set(uploads.map(row=>row.id)),ownMcp=new Set(tables.mcp_connections.map(row=>row.id));if(tables.branches.some(row=>!ownConversations.has(row.conversation_id)||(row.parent_branch_id&&!ownBranches.has(row.parent_branch_id))||(row.forked_from_message_id&&!ownMessages.has(row.forked_from_message_id)))||tables.messages.some(row=>!ownConversations.has(row.conversation_id))||tables.branch_messages.some(row=>!ownBranches.has(row.branch_id)||!ownMessages.has(row.message_id))||tables.artifact_storage_links.some(row=>!ownConversations.has(row.conversation_id)||!ownUploads.has(row.upload_id))||tables.message_attachments.some(row=>!ownMessages.has(row.message_id)||!ownUploads.has(row.upload_id))||tables.context_summaries.some(row=>!ownBranches.has(row.branch_id))||tables.mcp_tool_policies.some(row=>!ownMcp.has(row.connection_id))||conversations.some(row=>row.active_branch_id&&!ownBranches.has(row.active_branch_id)))throw new AuthError("백업 이미지의 데이터 연결이 올바르지 않습니다.",400);
  const previousUploads=all("SELECT id,size,deleted_at FROM uploads WHERE user_id=?",userId);const quotas=db.prepare("SELECT storage_quota_bytes AS active,trash_quota_bytes AS trash FROM users WHERE id=?").get(userId) as {active:number;trash:number};const existing=mode==="merge"?previousUploads:[],finalUploads=new Map(existing.map(row=>[String(row.id),row]));for(const row of uploads){const size=Number(row.size);if(!Number.isSafeInteger(size)||size<0)throw new AuthError("백업 이미지에 올바르지 않은 파일 크기가 있습니다.",400);finalUploads.set(String(row.id),row);}let activeBytes=0,trashBytes=0;for(const row of finalUploads.values())if(row.deleted_at)trashBytes+=Number(row.size);else activeBytes+=Number(row.size);if(activeBytes>quotas.active||trashBytes>quotas.trash)throw new AuthError("복원할 이미지가 현재 계정의 저장소 또는 휴지통 할당량을 초과합니다.",409);
  for(const row of uploads){const original=path.join(filesDir,`${row.id}.original`);if(!existsSync(original)||lstatSync(original).size!==Number(row.size))throw new AuthError(`미디어 ${row.id}의 원본 파일이 없거나 크기가 일치하지 않습니다.`,400);}
  const staged:Array<{temp:string;final:string;backup?:string;installed?:boolean}>=[];mkdirSync(uploadsDir,{recursive:true});try{for(const name of safeFileNames(uploads.map(row=>String(row.id)),filesDir)){const source=path.join(filesDir,name);const final=path.join(uploadsDir,name),temp=`${final}.${randomUUID()}.restore`;staged.push({temp,final});copyFileSync(source,temp);}
  db.transaction(()=>{if(mode==="replace"){db.prepare("DELETE FROM conversations WHERE user_id=?").run(userId);db.prepare("DELETE FROM uploads WHERE user_id=?").run(userId);db.prepare("DELETE FROM mcp_connections WHERE user_id=?").run(userId);}else{for(const row of conversations)db.prepare("DELETE FROM conversations WHERE id=? AND user_id=?").run(row.id,userId);for(const row of tables.mcp_connections)db.prepare("DELETE FROM mcp_connections WHERE user_id=? AND (id=? OR name=?)").run(userId,row.id,row.name);}for(const item of staged){if(existsSync(item.final)){item.backup=`${item.final}.${randomUUID()}.backup`;renameSync(item.final,item.backup);}renameSync(item.temp,item.final);item.installed=true;}for(const row of uploads){db.prepare(`INSERT INTO uploads(id,name,mime_type,size,width,height,created_at,user_id,retained,deleted_at) VALUES(@id,@name,@mime_type,@size,@width,@height,@created_at,@user_id,@retained,@deleted_at) ON CONFLICT(id) DO UPDATE SET name=excluded.name,mime_type=excluded.mime_type,size=excluded.size,width=excluded.width,height=excluded.height,created_at=excluded.created_at,user_id=excluded.user_id,retained=excluded.retained,deleted_at=excluded.deleted_at`).run({...row,deleted_at:row.deleted_at??null});}insertRows("conversations",conversations);insertRows("branches",tables.branches);insertRows("messages",tables.messages);insertRows("branch_messages",tables.branch_messages);insertRows("artifact_storage_links",tables.artifact_storage_links);insertRows("message_attachments",tables.message_attachments);insertRows("context_summaries",tables.context_summaries);insertRows("mcp_connections",tables.mcp_connections);insertRows("mcp_tool_policies",tables.mcp_tool_policies);if(data.profile){db.prepare("UPDATE users SET display_name=?,preferences=?,updated_at=? WHERE id=?").run(String(data.profile.displayName||"User"),String(data.profile.preferences||"{}"),new Date().toISOString(),userId);}})();for(const item of staged)if(item.backup){try{rmSync(item.backup,{force:true});}catch{}}if(mode==="replace"){const restored=new Set(uploads.map(row=>String(row.id))),removed=previousUploads.map(row=>String(row.id)).filter(id=>!restored.has(id));for(const name of safeFileNames(removed)){try{rmSync(path.join(uploadsDir,name),{force:true});}catch{}}}}
  catch(error){for(const item of staged){rmSync(item.temp,{force:true});if(item.installed)rmSync(item.final,{force:true});if(item.backup&&existsSync(item.backup)){rmSync(item.final,{force:true});renameSync(item.backup,item.final);}}throw error;}
}
function restoreAccounts(data:ImageData,actor:AuthUser,mode:RestoreMode){const source=data.tables||{},tables={users:sanitizedRows("users",source.users),plans:sanitizedRows("plans",source.plans),limits:sanitizedRows("plan_token_limits",source.plan_token_limits),credits:sanitizedRows("reset_credits",source.reset_credits),mcp:sanitizedRows("mcp_connections",source.mcp_connections??[]),mcpPolicies:sanitizedRows("mcp_tool_policies",source.mcp_tool_policies??[])};const remap=new Map<string,string>();for(const row of tables.users){const local=db.prepare("SELECT id FROM users WHERE username=? COLLATE NOCASE").get(row.username) as {id:string}|undefined;if(local)remap.set(String(row.id),local.id);}for(const row of tables.users){row.id=remap.get(String(row.id))||row.id;if(row.id===actor.id)row.role=actor.role;}for(const row of tables.credits){if(row.target_type==="user")row.target_id=remap.get(String(row.target_id))||row.target_id;row.created_by=remap.get(String(row.created_by))||row.created_by;}for(const row of tables.mcp)row.user_id=remap.get(String(row.user_id))||row.user_id;
  // Retain the destination operator so an image from another installation cannot lock them out.
  if(!tables.users.some(row=>row.id===actor.id)){const local=db.prepare(`SELECT ${accountColumns.join(",")} FROM users WHERE id=?`).get(actor.id) as Record<string,unknown>;tables.users.push({...local,plan_id:null});}
  const userIds=new Set(tables.users.map(row=>String(row.id))),planIds=new Set(tables.plans.map(row=>String(row.id)));
  for(const row of tables.users){const clash=db.prepare("SELECT id FROM users WHERE username=? COLLATE NOCASE AND id<>?").get(row.username,row.id) as {id:string}|undefined;if(clash&&(mode==="merge"||userIds.has(clash.id)))throw new AuthError(`이미지의 사용자 이름 ${String(row.username)}이(가) 현재 다른 계정에서 사용 중입니다.`,409);if(row.plan_id&&!planIds.has(String(row.plan_id))&&(mode==="replace"||!db.prepare("SELECT 1 FROM plans WHERE id=?").get(row.plan_id)))row.plan_id=null;}
  for(const row of tables.plans){const clash=db.prepare("SELECT id FROM plans WHERE name=? COLLATE NOCASE AND id<>?").get(row.name,row.id) as {id:string}|undefined;if(clash&&(mode==="merge"||planIds.has(clash.id)))throw new AuthError(`이미지의 플랜 이름 ${String(row.name)}이(가) 현재 다른 플랜에서 사용 중입니다.`,409);}
  if(tables.limits.some(row=>!planIds.has(String(row.plan_id))))throw new AuthError("이미지의 토큰 한도가 없는 플랜을 가리킵니다.",400);
  if(tables.mcp.some(row=>!userIds.has(String(row.user_id))))throw new AuthError("이미지의 MCP 연결이 없는 사용자를 가리킵니다.",400);
  const mcpIds=new Set(tables.mcp.map(row=>String(row.id)));if(tables.mcpPolicies.some(row=>!mcpIds.has(String(row.connection_id))))throw new AuthError("이미지의 MCP 도구 정책이 없는 연결을 가리킵니다.",400);
  for(const row of tables.credits)if(row.created_by&&!userIds.has(String(row.created_by))&&!db.prepare("SELECT 1 FROM users WHERE id=?").get(row.created_by))row.created_by=null;
  const removedUsers=mode==="replace"?(db.prepare("SELECT id FROM users").all() as Array<{id:string}>).map(row=>row.id).filter(id=>!userIds.has(id)):[];
  const removedUploads=removedUsers.length?(all(`SELECT id FROM uploads WHERE user_id IN (${placeholders(removedUsers)})`,...removedUsers)).map(row=>String(row.id)):[];
  db.transaction(()=>{if(mode==="replace"){if(removedUsers.length){for(const id of removedUsers){discardChatJobs(id);removeOwnedConfigEntries(id);}
      // Messages hold RESTRICT references to uploads, so conversations must go before their owners.
      db.prepare(`DELETE FROM conversations WHERE user_id IN (${placeholders(removedUsers)})`).run(...removedUsers);db.prepare(`DELETE FROM users WHERE id IN (${placeholders(removedUsers)})`).run(...removedUsers);}
      db.prepare("DELETE FROM plan_token_limits").run();db.prepare("DELETE FROM mcp_connections").run();const keep=[...planIds];db.prepare(keep.length?`DELETE FROM plans WHERE id NOT IN (${placeholders(keep)})`:"DELETE FROM plans").run(...keep);const credits=tables.credits.map(row=>row.id);db.prepare(credits.length?`DELETE FROM reset_credits WHERE id NOT IN (${placeholders(credits)})`:"DELETE FROM reset_credits").run(...credits);}
    else if(planIds.size)db.prepare(`DELETE FROM plan_token_limits WHERE plan_id IN (${placeholders([...planIds])})`).run(...planIds);
    if(mode==="merge")for(const row of tables.mcp)db.prepare("DELETE FROM mcp_connections WHERE id=? OR (user_id=? AND name=?)").run(row.id,row.user_id,row.name);upsertRows("plans",tables.plans,["id"]);upsertRows("plan_token_limits",tables.limits,["id"]);upsertRows("users",tables.users,["id"]);upsertRows("reset_credits",tables.credits,["id"]);insertRows("mcp_connections",tables.mcp);insertRows("mcp_tool_policies",tables.mcpPolicies);})();
  for(const name of safeFileNames(removedUploads))rmSync(path.join(uploadsDir,name),{force:true});
  return{removedUsers:removedUsers.length};
}
// Merge keeps connections and models that the image does not mention; the image wins for every identifier it carries.
function mergedConfig(current:Record<string,unknown>,incoming:Record<string,unknown>){const byId=(base:unknown,overlay:unknown)=>{const result=new Map<string,unknown>();for(const list of [base,overlay])if(Array.isArray(list))for(const item of list)if(item&&typeof item==="object"&&typeof (item as {id?:unknown}).id==="string")result.set((item as {id:string}).id,item);return[...result.values()];};const merged:Record<string,unknown>={...current,...incoming,connections:byId(current.connections,incoming.connections),models:byId(current.models,incoming.models)};const connections=merged.connections as Array<Record<string,unknown>>;for(const connection of connections)if(Array.isArray(connection.models)){const previous=(Array.isArray((current.connections as Array<Record<string,unknown>>|undefined))?(current.connections as Array<Record<string,unknown>>).find(item=>item.id===connection.id):undefined)?.models;connection.models=byId(previous,connection.models);}return merged;}

export async function restoreBackupImage(actor:AuthUser,archivePath:string,requestedScope:BackupScope,mode:RestoreMode,targetUserId?:string,credentials?:BackupCredentials){const userId=selectedUser(actor,requestedScope,targetUserId);if(!userId&&actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);if(requestedScope==="accounts"&&actor.role!=="superadmin")throw new AuthError("Superadmin access required.",403);const secret=validateCredentials(credentials);const temp=await mkdtemp(path.join(os.tmpdir(),"neural-restore-"));try{const decrypted=path.join(temp,"payload.7z");await decryptBackup(archivePath,decrypted,secret);archivePath=decrypted;const handle=await open(/* turbopackIgnore: true */ archivePath,"r");const header=Buffer.alloc(6);try{await handle.read(header,0,6,0);}finally{await handle.close();}if(header.toString("hex")!=="377abcaf271c")throw new AuthError("올바른 7z 백업 이미지가 아닙니다.",400);await validateArchiveListing(archivePath,temp);await run7z(["x","-y",`-o${temp}`,archivePath]);validateExtracted(temp);const manifest=manifestSchema.parse(JSON.parse(readFileSync(path.join(temp,"manifest.json"),"utf8")));if(manifest.imageVersion>BACKUP_IMAGE_VERSION)throw new AuthError(`이미지 버전 ${manifest.imageVersion}은(는) 현재 시스템 버전 ${BACKUP_IMAGE_VERSION}보다 새 버전이라 복원할 수 없습니다.`,400);if(manifest.scope!==requestedScope&&!(["personal","user"].includes(manifest.scope)&&["personal","user"].includes(requestedScope)))throw new AuthError(`요청한 ${requestedScope} 범위와 이미지의 ${manifest.scope} 범위가 다릅니다.`,400);let modelSettings:ModelSettingsOutcome|undefined;let data=migrateImage(manifest.imageVersion,JSON.parse(readFileSync(path.join(temp,manifest.dataFile),"utf8")) as ImageData);if(userId){if(manifest.owner?.id!==userId)data=remapPersonal(data,userId,path.join(temp,"files"));data=await renameRestoredAliases(data,userId,mode);discardChatJobs(userId);personalRestore(data,userId,mode,path.join(temp,"files"));modelSettings=await restorePersonalModelSettings(data,userId,mode);}else if(requestedScope==="global"){if(actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);if(!data.config)throw new AuthError("전역 설정 데이터가 없습니다.",400);const current=JSON.parse((db.prepare("SELECT value FROM app_config WHERE id=1").get() as {value:string}|undefined)?.value||"{}") as Record<string,unknown>;await writeConfig(mode==="merge"?mergedConfig(current,data.config):data.config);}else{if(actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);restoreAccounts(data,actor,mode);}if(requestedScope!=="personal")logAdminAudit(actor.id,userId||actor.id,`restore.${requestedScope}`,JSON.stringify({mode,imageVersion:manifest.imageVersion}));return{restored:true,imageVersion:manifest.imageVersion,systemImageVersion:BACKUP_IMAGE_VERSION,...(modelSettings?{modelSettings}:{})};}finally{await rm(temp,{recursive:true,force:true}).catch(()=>undefined);}}
