import { randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { existsSync, lstatSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync, copyFileSync, readdirSync } from "node:fs";
import { mkdtemp, open, rm, writeFile, mkdir, copyFile, statfs } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { path7za } from "7zip-bin";
import { z } from "zod";
import { AuthError, type AuthUser, logAdminAudit } from "./auth";
import { dataDir, db } from "./database";
import { writeConfig } from "./config";
import { discardChatJobs } from "./chat-disposal";

export const BACKUP_IMAGE_VERSION=1;
export type BackupScope="personal"|"global"|"accounts"|"user";
type RestoreMode="merge"|"replace";
type ImageData={profile?:Record<string,unknown>;tables?:Record<string,Array<Record<string,unknown>>>;config?:Record<string,unknown>};
type Manifest={format:"neuralnetui-backup";imageVersion:number;appVersion:string;scope:BackupScope;createdAt:string;owner?:{id:string;username:string};dataFile:"data.json"};
const manifestSchema=z.object({format:z.literal("neuralnetui-backup"),imageVersion:z.number().int().nonnegative(),appVersion:z.string(),scope:z.enum(["personal","global","accounts","user"]),createdAt:z.string(),owner:z.object({id:z.string(),username:z.string()}).optional(),dataFile:z.literal("data.json")});
const uploadsDir=path.join(dataDir,"uploads");
const personalTables=["conversations","branches","messages","branch_messages","uploads","message_attachments","context_summaries"] as const;
const accountColumns=["id","username","display_name","password_hash","role","preferences","storage_quota_bytes","trash_quota_bytes","storage_quota_uses_default","trash_quota_uses_default","audit_enabled","plan_id","created_at","updated_at"];
const tableColumns:Record<string,string[]>={
  conversations:["id","title","model_id","reasoning_preset_id","active_branch_id","created_at","updated_at","user_id","title_managed","temporary","deleted_at"],
  branches:["id","conversation_id","name","parent_branch_id","forked_from_message_id","position","created_at","updated_at"],
  messages:["id","conversation_id","revision_group_id","role","content","reasoning","reasoning_duration_seconds","created_at","input_tokens","output_tokens","reasoning_tokens","total_tokens","completion_duration_seconds","time_to_first_token_seconds","tool_events","context_tokens","steps"],
  branch_messages:["branch_id","message_id","position"],uploads:["id","name","mime_type","size","width","height","created_at","user_id","retained","deleted_at"],message_attachments:["message_id","upload_id","position"],context_summaries:["branch_id","fingerprint","covered_count","summary"],
  users:accountColumns,plans:["id","name","storage_quota_bytes","served_model_ids","model_weights","created_at","updated_at"],plan_token_limits:["id","plan_id","duration_seconds","token_limit","token_scope","position"],reset_credits:["id","target_type","target_id","max_window_seconds","expires_at","title","created_at","created_by"],
};
function sanitizedRows(table:string,value:unknown){if(!Array.isArray(value))throw new AuthError(`백업 이미지에 ${table} 데이터가 없습니다.`,400);const allowed=tableColumns[table];if(!allowed)throw new AuthError("지원하지 않는 백업 데이터입니다.",400);return value.map((candidate,index)=>{if(!candidate||typeof candidate!=="object"||Array.isArray(candidate))throw new AuthError(`${table}의 ${index+1}번째 항목이 올바르지 않습니다.`,400);const row:Record<string,unknown>={};for(const column of allowed)if(Object.hasOwn(candidate,column))row[column]=(candidate as Record<string,unknown>)[column];return row;});}

function bundled7z(){const relative=process.platform==="win32"?path.join("win",process.arch,"7za.exe"):process.platform==="darwin"?path.join("mac",process.arch,"7za"):path.join("linux",process.arch,"7za");const candidate=path.join(process.cwd(),"node_modules","7zip-bin",relative);return existsSync(candidate)?candidate:path7za;}
function run7zCapture(args:string[],cwd?:string){return new Promise<string>((resolve,reject)=>{const child=spawn(bundled7z(),args,{cwd,windowsHide:true,stdio:["ignore","pipe","pipe"]});let output="",error="";child.stdout.on("data",chunk=>{output+=chunk;if(output.length>64*1024**2){child.kill();reject(new AuthError("백업 이미지 항목 목록이 너무 큽니다.",413));}});child.stderr.on("data",chunk=>{error=(error+chunk).slice(-8000);});child.once("error",reject);child.once("exit",code=>code===0?resolve(output):reject(new Error(`7z failed with code ${code}: ${error}`)));});}
async function run7z(args:string[],cwd?:string){await run7zCapture(args,cwd);}
async function validateArchiveListing(archivePath:string,extractRoot:string){const listing=await run7zCapture(["l","-slt",archivePath]);const details=listing.slice(Math.max(0,listing.indexOf("----------")));const paths=[...details.matchAll(/^Path = (.+)$/gm)].map(match=>match[1].trim());if(!paths.length||paths.length>2_000_000)throw new AuthError("백업 이미지의 항목 수가 올바르지 않습니다.",413);for(const entry of paths){if(entry.includes(":")||entry.startsWith("/")||entry.startsWith("\\")||entry.split(/[\\/]/).some(part=>part===".."))throw new AuthError("백업 이미지에 안전하지 않은 경로가 있습니다.",400);}const unpacked=[...details.matchAll(/^Size = (\d+)$/gm)].reduce((sum,match)=>sum+Number(match[1]),0);const disk=await statfs(extractRoot);const available=Number(disk.bavail)*Number(disk.bsize);if(!Number.isSafeInteger(unpacked)||unpacked>10*1024**4||unpacked>available*.8)throw new AuthError("백업 이미지의 압축 해제 크기가 시스템 한도를 초과합니다.",413);}
function all(sql:string,...args:unknown[]){return db.prepare(sql).all(...args) as Array<Record<string,unknown>>;}
function placeholders(values:unknown[]){return values.map(()=>"?").join(",");}
function userData(userId:string):ImageData{
  const conversations=all("SELECT * FROM conversations WHERE user_id=?",userId);
  const conversationIds=conversations.map(row=>row.id);
  const branches=conversationIds.length?all(`SELECT * FROM branches WHERE conversation_id IN (${placeholders(conversationIds)})`,...conversationIds):[];
  const branchIds=branches.map(row=>row.id);
  const messages=conversationIds.length?all(`SELECT * FROM messages WHERE conversation_id IN (${placeholders(conversationIds)})`,...conversationIds):[];
  const messageIds=messages.map(row=>row.id);
  const uploads=all("SELECT * FROM uploads WHERE user_id=?",userId);
  const user=db.prepare("SELECT display_name,preferences FROM users WHERE id=?").get(userId) as {display_name:string;preferences:string};
  return {profile:{displayName:user.display_name,preferences:user.preferences},tables:{
    conversations,branches,messages,
    branch_messages:branchIds.length?all(`SELECT * FROM branch_messages WHERE branch_id IN (${placeholders(branchIds)})`,...branchIds):[],
    uploads,
    message_attachments:messageIds.length?all(`SELECT * FROM message_attachments WHERE message_id IN (${placeholders(messageIds)})`,...messageIds):[],
    context_summaries:branchIds.length?all(`SELECT * FROM context_summaries WHERE branch_id IN (${placeholders(branchIds)})`,...branchIds):[],
  }};
}
function safeFileNames(ids:string[],directory=uploadsDir){const allowed=new Set(ids);return existsSync(directory)?readdirSync(directory).filter(name=>{const id=name.split(".")[0];return allowed.has(id)&&/^[a-zA-Z0-9_-]+\.[a-zA-Z0-9_.-]+$/.test(name);}):[];}
function selectedUser(actor:AuthUser,scope:BackupScope,targetUserId?:string){if(scope==="personal")return actor.id;if(scope==="user"){if(actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);if(!targetUserId||!db.prepare("SELECT 1 FROM users WHERE id=?").get(targetUserId))throw new AuthError("사용자를 찾을 수 없습니다.",404);return targetUserId;}return undefined;}

export async function createBackupImage(actor:AuthUser,scope:BackupScope,appVersion:string,targetUserId?:string){const userId=selectedUser(actor,scope,targetUserId);if((scope==="global"||scope==="accounts")&&actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);const temp=await mkdtemp(path.join(os.tmpdir(),"neural-backup-"));try{const content=path.join(temp,"content");const archive=path.join(temp,`NeuralNetUI-${scope}-${new Date().toISOString().replace(/[:.]/g,"-")}.7z`);await mkdir(content,{recursive:true});let data:ImageData;let owner:Manifest["owner"];
    if(userId){const row=db.prepare("SELECT username FROM users WHERE id=?").get(userId) as {username:string};data=userData(userId);owner={id:userId,username:row.username};const files=path.join(content,"files");await mkdir(files,{recursive:true});const uploadIds=(data.tables?.uploads||[]).map(item=>String(item.id));for(const id of uploadIds)if(!existsSync(path.join(uploadsDir,`${id}.original`)))throw new AuthError(`저장된 미디어 ${id}의 원본 파일을 찾을 수 없습니다.`,409);for(const name of safeFileNames(uploadIds))await copyFile(path.join(uploadsDir,name),path.join(files,name));}
    else if(scope==="global"){const value=(db.prepare("SELECT value FROM app_config WHERE id=1").get() as {value:string}|undefined)?.value||"{}";data={config:JSON.parse(value)};}
    else data={tables:{users:all(`SELECT ${accountColumns.join(",")} FROM users`),plans:all("SELECT * FROM plans"),plan_token_limits:all("SELECT * FROM plan_token_limits"),reset_credits:all("SELECT * FROM reset_credits")}};
    const manifest:Manifest={format:"neuralnetui-backup",imageVersion:BACKUP_IMAGE_VERSION,appVersion,scope,createdAt:new Date().toISOString(),...(owner?{owner}:{}),dataFile:"data.json"};await writeFile(path.join(content,"manifest.json"),JSON.stringify(manifest,null,2),"utf8");await writeFile(path.join(content,"data.json"),JSON.stringify(data),"utf8");await run7z(["a","-t7z","-mx=9","-m0=lzma2","-mmt=on",archive,"."],content);if(scope!=="personal")logAdminAudit(actor.id,userId||actor.id,`backup.${scope}`);return{path:archive,name:path.basename(archive),cleanup:()=>rm(temp,{recursive:true,force:true})};
  }catch(error){await rm(temp,{recursive:true,force:true}).catch(()=>undefined);throw error;}}

function migrateImage(version:number,data:ImageData){let current=version;let migrated=data;while(current<BACKUP_IMAGE_VERSION){if(current===0){migrated={...migrated,tables:migrated.tables||{}};current=1;continue;}throw new AuthError(`이미지 버전 ${current}에서 ${current+1}(으)로 승계할 어댑터가 없습니다.`,400);}return migrated;}
function validateExtracted(root:string){const walk=(directory:string)=>{for(const entry of readdirSync(directory,{withFileTypes:true})){const full=path.join(directory,entry.name);const relative=path.relative(root,full);if(relative.startsWith("..")||path.isAbsolute(relative))throw new AuthError("백업 이미지에 안전하지 않은 경로가 있습니다.",400);const stats=lstatSync(full);if(stats.isSymbolicLink())throw new AuthError("백업 이미지에 심볼릭 링크를 사용할 수 없습니다.",400);if(stats.isDirectory())walk(full);}};walk(root);}
function insertRows(table:string,rows:Array<Record<string,unknown>>,mode:"insert"|"replace"="insert"){if(!rows.length)return;const columns=Object.keys(rows[0]);const statement=db.prepare(`${mode==="replace"?"INSERT OR REPLACE":"INSERT"} INTO ${table}(${columns.join(",")}) VALUES (${columns.map(column=>`@${column}`).join(",")})`);for(const row of rows)statement.run(row);}
function upsertRows(table:string,rows:Array<Record<string,unknown>>,conflict:string[]){if(!rows.length)return;const columns=Object.keys(rows[0]),updates=columns.filter(column=>!conflict.includes(column)).map(column=>`${column}=excluded.${column}`).join(",");const statement=db.prepare(`INSERT INTO ${table}(${columns.join(",")}) VALUES (${columns.map(column=>`@${column}`).join(",")}) ON CONFLICT(${conflict.join(",")}) DO UPDATE SET ${updates}`);for(const row of rows)statement.run(row);}
function personalRestore(data:ImageData,userId:string,mode:RestoreMode,filesDir:string){const source=data.tables||{},tables=Object.fromEntries(personalTables.map(table=>[table,sanitizedRows(table,source[table])])) as Record<(typeof personalTables)[number],Array<Record<string,unknown>>>;const conversations=tables.conversations;const uploads=tables.uploads;for(const row of conversations)row.user_id=userId;for(const row of uploads)row.user_id=userId;for(const row of [...conversations,...uploads])if(!/^[a-zA-Z0-9_-]{1,200}$/.test(String(row.id||"")))throw new AuthError("백업 이미지에 올바르지 않은 데이터 식별자가 있습니다.",400);const foreignConversation=conversations.find(row=>{const existing=db.prepare("SELECT user_id FROM conversations WHERE id=?").get(row.id) as {user_id:string}|undefined;return existing&&existing.user_id!==userId;});const foreignUpload=uploads.find(row=>{const existing=db.prepare("SELECT user_id FROM uploads WHERE id=?").get(row.id) as {user_id:string}|undefined;return existing&&existing.user_id!==userId;});if(foreignConversation||foreignUpload)throw new AuthError("다른 사용자의 데이터와 식별자가 충돌합니다.",409);
  const previousUploads=all("SELECT id,size,deleted_at FROM uploads WHERE user_id=?",userId);const quotas=db.prepare("SELECT storage_quota_bytes AS active,trash_quota_bytes AS trash FROM users WHERE id=?").get(userId) as {active:number;trash:number};const existing=mode==="merge"?previousUploads:[],finalUploads=new Map(existing.map(row=>[String(row.id),row]));for(const row of uploads){const size=Number(row.size);if(!Number.isSafeInteger(size)||size<0)throw new AuthError("백업 이미지에 올바르지 않은 파일 크기가 있습니다.",400);finalUploads.set(String(row.id),row);}let activeBytes=0,trashBytes=0;for(const row of finalUploads.values())if(row.deleted_at)trashBytes+=Number(row.size);else activeBytes+=Number(row.size);if(activeBytes>quotas.active||trashBytes>quotas.trash)throw new AuthError("복원할 이미지가 현재 계정의 저장소 또는 휴지통 할당량을 초과합니다.",409);
  for(const row of uploads){const original=path.join(filesDir,`${row.id}.original`);if(!existsSync(original)||lstatSync(original).size!==Number(row.size))throw new AuthError(`미디어 ${row.id}의 원본 파일이 없거나 크기가 일치하지 않습니다.`,400);}
  const staged:Array<{temp:string;final:string;backup?:string}>=[];mkdirSync(uploadsDir,{recursive:true});for(const name of safeFileNames(uploads.map(row=>String(row.id)),filesDir)){const source=path.join(filesDir,name);const final=path.join(uploadsDir,name),temp=`${final}.${randomUUID()}.restore`;copyFileSync(source,temp);staged.push({temp,final});}
  try{db.transaction(()=>{if(mode==="replace"){db.prepare("DELETE FROM conversations WHERE user_id=?").run(userId);db.prepare("DELETE FROM uploads WHERE user_id=?").run(userId);}else{for(const row of conversations)db.prepare("DELETE FROM conversations WHERE id=? AND user_id=?").run(row.id,userId);}for(const item of staged){if(existsSync(item.final)){item.backup=`${item.final}.${randomUUID()}.backup`;renameSync(item.final,item.backup);}renameSync(item.temp,item.final);}for(const row of uploads){db.prepare(`INSERT INTO uploads(id,name,mime_type,size,width,height,created_at,user_id,retained,deleted_at) VALUES(@id,@name,@mime_type,@size,@width,@height,@created_at,@user_id,@retained,@deleted_at) ON CONFLICT(id) DO UPDATE SET name=excluded.name,mime_type=excluded.mime_type,size=excluded.size,width=excluded.width,height=excluded.height,created_at=excluded.created_at,user_id=excluded.user_id,retained=excluded.retained,deleted_at=excluded.deleted_at`).run({...row,deleted_at:row.deleted_at??null});}insertRows("conversations",conversations);insertRows("branches",tables.branches);insertRows("messages",tables.messages);insertRows("branch_messages",tables.branch_messages);insertRows("message_attachments",tables.message_attachments);insertRows("context_summaries",tables.context_summaries);if(data.profile){db.prepare("UPDATE users SET display_name=?,preferences=?,updated_at=? WHERE id=?").run(String(data.profile.displayName||"User"),String(data.profile.preferences||"{}"),new Date().toISOString(),userId);}})();for(const item of staged)if(item.backup)rmSync(item.backup,{force:true});if(mode==="replace"){const restored=new Set(uploads.map(row=>String(row.id))),removed=previousUploads.map(row=>String(row.id)).filter(id=>!restored.has(id));for(const name of safeFileNames(removed))rmSync(path.join(uploadsDir,name),{force:true});}}
  catch(error){for(const item of staged){rmSync(item.temp,{force:true});if(item.backup&&existsSync(item.backup)){rmSync(item.final,{force:true});renameSync(item.backup,item.final);}}throw error;}
}
function restoreAccounts(data:ImageData,actor:AuthUser,mode:RestoreMode){const source=data.tables||{},tables={users:sanitizedRows("users",source.users),plans:sanitizedRows("plans",source.plans),limits:sanitizedRows("plan_token_limits",source.plan_token_limits),credits:sanitizedRows("reset_credits",source.reset_credits)};if(!tables.users.some(row=>row.id===actor.id))throw new AuthError("현재 관리자 계정이 없는 인증 이미지로는 복원할 수 없습니다.",409);db.transaction(()=>{if(mode==="replace"){const ids=tables.users.map(row=>row.id);db.prepare(`DELETE FROM users WHERE id NOT IN (${placeholders(ids)})`).run(...ids);db.prepare("DELETE FROM plan_token_limits").run();const planIds=tables.plans.map(row=>row.id);if(planIds.length)db.prepare(`DELETE FROM plans WHERE id NOT IN (${placeholders(planIds)})`).run(...planIds);}upsertRows("plans",tables.plans,["id"]);upsertRows("plan_token_limits",tables.limits,["id"]);upsertRows("users",tables.users,["id"]);upsertRows("reset_credits",tables.credits,["id"]);})();}

export async function restoreBackupImage(actor:AuthUser,archivePath:string,requestedScope:BackupScope,mode:RestoreMode,targetUserId?:string){const temp=await mkdtemp(path.join(os.tmpdir(),"neural-restore-"));try{const handle=await open(archivePath,"r");const header=Buffer.alloc(6);try{await handle.read(header,0,6,0);}finally{await handle.close();}if(header.toString("hex")!=="377abcaf271c")throw new AuthError("올바른 7z 백업 이미지가 아닙니다.",400);await validateArchiveListing(archivePath,temp);await run7z(["x","-y",`-o${temp}`,archivePath]);validateExtracted(temp);const manifest=manifestSchema.parse(JSON.parse(readFileSync(path.join(temp,"manifest.json"),"utf8")));if(manifest.imageVersion>BACKUP_IMAGE_VERSION)throw new AuthError(`이미지 버전 ${manifest.imageVersion}은(는) 현재 시스템 버전 ${BACKUP_IMAGE_VERSION}보다 새 버전이라 복원할 수 없습니다.`,400);if(manifest.scope!==requestedScope)throw new AuthError(`요청한 ${requestedScope} 범위와 이미지의 ${manifest.scope} 범위가 다릅니다.`,400);const data=migrateImage(manifest.imageVersion,JSON.parse(readFileSync(path.join(temp,manifest.dataFile),"utf8")) as ImageData);const userId=selectedUser(actor,requestedScope,targetUserId);if(userId){discardChatJobs(userId);personalRestore(data,userId,mode,path.join(temp,"files"));}else if(requestedScope==="global"){if(actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);if(!data.config)throw new AuthError("전역 설정 데이터가 없습니다.",400);await writeConfig(data.config);}else{if(actor.role!=="admin"&&actor.role!=="superadmin")throw new AuthError("Administrator access required.",403);restoreAccounts(data,actor,mode);}if(requestedScope!=="personal")logAdminAudit(actor.id,userId||actor.id,`restore.${requestedScope}`,JSON.stringify({mode,imageVersion:manifest.imageVersion}));return{restored:true,imageVersion:manifest.imageVersion,systemImageVersion:BACKUP_IMAGE_VERSION};}finally{await rm(temp,{recursive:true,force:true}).catch(()=>undefined);}}
