import { randomUUID } from "node:crypto";
import { z } from "zod";
import { AuthError, type AuthUser, logAdminAudit } from "./auth";
import { db } from "./database";
import type { ResetCredit, TokenScope, UsagePlan, UsageStatus, UsageWindowStatus } from "./types";
import { anchoredWindow, firstUseAt, hasTwoDecimalPlaces, type LiveTokenUsage, MAX_MODEL_WEIGHT, modelAllowedByPlan, normalizeModelWeight, weightedTokenUsage } from "./plan-usage";

type PlanRow={id:string;name:string;storage_quota_bytes:number;trash_quota_bytes:number;served_model_ids:string;model_weights:string;mcp_enabled:number;max_mcp_connections:number;artifact_html_enabled:number;user_count?:number};
type LimitRow={id:string;plan_id:string;duration_seconds:number;token_limit:number;token_scope:TokenScope;position:number};
const limitSchema=z.object({id:z.string().min(1).max(100).optional(),durationSeconds:z.number().int().min(3600).max(31536000),tokenLimit:z.number().int().positive().max(10_000_000_000),tokenScope:z.enum(["input","output","both"])});
const planSchema=z.object({name:z.string().trim().min(1).max(80),storageQuotaBytes:z.number().int().min(1024**2).max(10*1024**4),trashQuotaBytes:z.number().int().min(1024**2).max(20*1024**4).optional(),servedModelIds:z.array(z.string().min(1).max(500)).max(500),modelWeights:z.record(z.string(),z.number().min(.01).max(MAX_MODEL_WEIGHT).refine(hasTwoDecimalPlaces,"가중치는 소수점 둘째 자리까지 입력할 수 있습니다.")).default({}),tokenLimits:z.array(limitSchema).max(32),mcpEnabled:z.boolean().default(false),maxMcpConnections:z.number().int().min(0).max(100).default(0),artifactHtmlEnabled:z.boolean().optional()});

declare global { var neuralLiveTokenUsage: Map<string,Map<string,LiveTokenUsage>>|undefined; }
const liveUsage=globalThis.neuralLiveTokenUsage??new Map<string,Map<string,LiveTokenUsage>>();
globalThis.neuralLiveTokenUsage=liveUsage;
/** Tracks a response that is still streaming so a manual usage refresh includes the tokens produced so far. */
export function setLiveTokenUsage(userId:string,key:string,modelId:string,inputTokens:number,outputTokens:number){const entries=liveUsage.get(userId)??new Map<string,LiveTokenUsage>();const previous=entries.get(key);entries.set(key,{modelId,inputTokens:Math.max(0,Math.floor(inputTokens)),outputTokens:Math.max(0,Math.floor(outputTokens)),startedAt:previous?.startedAt??Date.now()});liveUsage.set(userId,entries);}
export function clearLiveTokenUsage(userId:string,key:string){const entries=liveUsage.get(userId);if(!entries)return;entries.delete(key);if(!entries.size)liveUsage.delete(userId);}
function liveEntries(userId:string){return [...(liveUsage.get(userId)?.values()||[])];}

function parseJson<T>(value:string,fallback:T):T{try{return JSON.parse(value) as T;}catch{return fallback;}}
function mapPlan(row:PlanRow,limits:LimitRow[]):UsagePlan{return{id:row.id,name:row.name,storageQuotaBytes:row.storage_quota_bytes,trashQuotaBytes:row.trash_quota_bytes,servedModelIds:parseJson(row.served_model_ids,[]),modelWeights:parseJson(row.model_weights,{}),tokenLimits:limits.filter(item=>item.plan_id===row.id).sort((a,b)=>a.position-b.position).map(item=>({id:item.id,durationSeconds:item.duration_seconds,tokenLimit:item.token_limit,tokenScope:item.token_scope})),mcpEnabled:row.mcp_enabled===1,maxMcpConnections:row.max_mcp_connections||0,artifactHtmlEnabled:row.artifact_html_enabled===1,...(row.user_count===undefined?{}:{userCount:row.user_count})};}

export function listPlans():UsagePlan[]{const rows=db.prepare(`SELECT p.*,COUNT(u.id) AS user_count FROM plans p LEFT JOIN users u ON u.plan_id=p.id GROUP BY p.id ORDER BY p.created_at,p.name`).all() as PlanRow[];const limits=db.prepare("SELECT * FROM plan_token_limits ORDER BY position").all() as LimitRow[];return rows.map(row=>mapPlan(row,limits));}
export function getPlan(id:string):UsagePlan|undefined{const row=db.prepare("SELECT * FROM plans WHERE id=?").get(id) as PlanRow|undefined;if(!row)return;return mapPlan(row,db.prepare("SELECT * FROM plan_token_limits WHERE plan_id=? ORDER BY position").all(id) as LimitRow[]);}

export function savePlan(input:unknown,id?:string){const parsed=planSchema.parse(input);const value={...parsed,trashQuotaBytes:parsed.trashQuotaBytes??Math.min(20*1024**4,parsed.storageQuotaBytes*2),artifactHtmlEnabled:parsed.artifactHtmlEnabled??(id?getPlan(id)?.artifactHtmlEnabled??true:true)};const planId=id||randomUUID();const stamp=new Date().toISOString();db.transaction(()=>{const existing=id&&db.prepare("SELECT 1 FROM plans WHERE id=?").get(id);if(id&&!existing)throw new AuthError("플랜을 찾을 수 없습니다.",404);db.prepare(`INSERT INTO plans(id,name,storage_quota_bytes,trash_quota_bytes,served_model_ids,model_weights,mcp_enabled,max_mcp_connections,artifact_html_enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,storage_quota_bytes=excluded.storage_quota_bytes,trash_quota_bytes=excluded.trash_quota_bytes,served_model_ids=excluded.served_model_ids,model_weights=excluded.model_weights,mcp_enabled=excluded.mcp_enabled,max_mcp_connections=excluded.max_mcp_connections,artifact_html_enabled=excluded.artifact_html_enabled,updated_at=excluded.updated_at`).run(planId,value.name,value.storageQuotaBytes,value.trashQuotaBytes,JSON.stringify(value.servedModelIds),JSON.stringify(Object.fromEntries(Object.entries(value.modelWeights).map(([key,weight])=>[key,normalizeModelWeight(weight)]))),value.mcpEnabled?1:0,value.mcpEnabled?value.maxMcpConnections:0,value.artifactHtmlEnabled?1:0,stamp,stamp);db.prepare("DELETE FROM plan_token_limits WHERE plan_id=?").run(planId);const insert=db.prepare("INSERT INTO plan_token_limits(id,plan_id,duration_seconds,token_limit,token_scope,position) VALUES(?,?,?,?,?,?)");value.tokenLimits.forEach((limit,index)=>insert.run(limit.id||randomUUID(),planId,limit.durationSeconds,limit.tokenLimit,limit.tokenScope,index));const over=db.prepare(`SELECT u.username FROM users u WHERE u.plan_id=? AND (SELECT COALESCE(SUM(size),0) FROM uploads WHERE user_id=u.id AND deleted_at IS NULL)>? LIMIT 1`).get(planId,value.storageQuotaBytes) as {username:string}|undefined;if(over)throw new AuthError(`${over.username} 사용자의 현재 저장소 사용량보다 플랜 용량이 작습니다.`,409);if(value.mcpEnabled){const mcpOver=db.prepare(`SELECT u.username FROM users u WHERE u.plan_id=? AND (SELECT COUNT(*) FROM mcp_connections m WHERE m.user_id=u.id)>? LIMIT 1`).get(planId,value.maxMcpConnections) as {username:string}|undefined;if(mcpOver)throw new AuthError(`${mcpOver.username} 사용자가 등록한 MCP 수보다 플랜 한도가 작습니다.`,409);}db.prepare("UPDATE users SET storage_quota_bytes=?,trash_quota_bytes=?,storage_quota_uses_default=0,trash_quota_uses_default=0,updated_at=? WHERE plan_id=?").run(value.storageQuotaBytes,value.trashQuotaBytes,stamp,planId);})();return getPlan(planId)!;}

/** HTML preview policy for the current account. No plan means no script execution. */
export function artifactHtmlAllowed(userId:string){const row=db.prepare("SELECT p.artifact_html_enabled AS enabled FROM users u LEFT JOIN plans p ON p.id=u.plan_id WHERE u.id=?").get(userId) as {enabled:number|null}|undefined;return row?.enabled===1;}
export function deletePlan(id:string){const count=(db.prepare("SELECT COUNT(*) AS count FROM plans").get() as {count:number}).count;if(count<=1)throw new AuthError("마지막 플랜은 삭제할 수 없습니다.",409);const replacement=db.prepare("SELECT id,storage_quota_bytes AS storage,trash_quota_bytes AS trash,mcp_enabled AS mcpEnabled,max_mcp_connections AS mcpMaximum FROM plans WHERE id<>? ORDER BY storage_quota_bytes DESC,created_at LIMIT 1").get(id) as {id:string;storage:number;trash:number;mcpEnabled:number;mcpMaximum:number}|undefined;if(!replacement)throw new AuthError("대체 플랜을 찾을 수 없습니다.",409);const over=db.prepare(`SELECT u.username FROM users u WHERE u.plan_id=? AND (SELECT COALESCE(SUM(size),0) FROM uploads WHERE user_id=u.id AND deleted_at IS NULL)>? LIMIT 1`).get(id,replacement.storage) as {username:string}|undefined;if(over)throw new AuthError(`${over.username} 사용자의 데이터가 대체 플랜 저장소 용량을 초과합니다.`,409);if(replacement.mcpEnabled){const mcpOver=db.prepare(`SELECT u.username FROM users u WHERE u.plan_id=? AND (SELECT COUNT(*) FROM mcp_connections m WHERE m.user_id=u.id)>? LIMIT 1`).get(id,replacement.mcpMaximum) as {username:string}|undefined;if(mcpOver)throw new AuthError(`${mcpOver.username} 사용자의 MCP 연결 수가 대체 플랜 한도를 초과합니다.`,409);}db.transaction(()=>{db.prepare("UPDATE users SET plan_id=?,storage_quota_bytes=?,trash_quota_bytes=?,storage_quota_uses_default=0,trash_quota_uses_default=0 WHERE plan_id=?").run(replacement.id,replacement.storage,replacement.trash,id);const result=db.prepare("DELETE FROM plans WHERE id=?").run(id);if(!result.changes)throw new AuthError("플랜을 찾을 수 없습니다.",404);})();}

function userPlan(userId:string){const row=db.prepare("SELECT plan_id FROM users WHERE id=?").get(userId) as {plan_id:string|null}|undefined;return row?.plan_id?getPlan(row.plan_id):undefined;}
function applicableReset(userId:string,duration:number){return(db.prepare("SELECT reset_at FROM token_usage_resets WHERE user_id=? AND max_window_seconds>=? ORDER BY reset_at DESC LIMIT 1").get(userId,duration) as {reset_at:string}|undefined)?.reset_at;}
// A reset credit empties every window it covers; each starts again at the first use after the reset,
// while longer windows keep their usage and timing.
function windowStatus(userId:string,plan:UsagePlan,limit:UsagePlan["tokenLimits"][number],at=new Date(),live:LiveTokenUsage[]=[]):UsageWindowStatus{const reset=applicableReset(userId,limit.durationSeconds);const first=db.prepare(`SELECT created_at FROM token_usage_events WHERE user_id=? AND (? IS NULL OR created_at>?) ORDER BY created_at LIMIT 1`).get(userId,reset??null,reset??null) as {created_at:string}|undefined;const firstAt=firstUseAt(first?new Date(first.created_at).getTime():undefined,live,reset?new Date(reset).getTime():undefined);if(firstAt===undefined)return{...limit,usedTokens:0,percentage:0};const window=anchoredWindow(firstAt,at.getTime(),limit.durationSeconds),start=new Date(window.startsAt);const events=db.prepare("SELECT model_id,input_tokens,output_tokens FROM token_usage_events WHERE user_id=? AND created_at>=? AND created_at<=?").all(userId,start.toISOString(),at.toISOString()) as Array<{model_id:string;input_tokens:number;output_tokens:number}>;const used=weightedTokenUsage([...events.map(event=>({modelId:event.model_id,inputTokens:event.input_tokens,outputTokens:event.output_tokens})),...live],limit.tokenScope,plan.modelWeights);return{...limit,usedTokens:used,percentage:Math.min(100,used/limit.tokenLimit*100),startsAt:start.toISOString(),resetsAt:new Date(window.resetsAt).toISOString()};}
function creditsFor(userId:string,planId?:string,at=new Date()):ResetCredit[]{return(db.prepare(`SELECT c.* FROM reset_credits c LEFT JOIN reset_credit_redemptions r ON r.credit_id=c.id AND r.user_id=? WHERE r.credit_id IS NULL AND c.expires_at>? AND ((c.target_type='user' AND c.target_id=?) OR (c.target_type='plan' AND c.target_id=?)) ORDER BY c.expires_at`).all(userId,at.toISOString(),userId,planId||"") as Array<{id:string;title:string;max_window_seconds:number;expires_at:string;target_type:"user"|"plan";target_id:string}>).map(row=>({id:row.id,title:row.title,maxWindowSeconds:row.max_window_seconds,expiresAt:row.expires_at,targetType:row.target_type,targetId:row.target_id}));}
/** `includeLive` adds responses still streaming; admission and output limits use recorded usage only. */
export function usageStatus(userId:string,at=new Date(),includeLive=false):UsageStatus{const plan=userPlan(userId);if(!plan)return{windows:[],nearestPercentage:0,blocked:false,credits:[]};const live=includeLive?liveEntries(userId):[];const windows=plan.tokenLimits.map(limit=>windowStatus(userId,plan,limit,at,live));const nearestPercentage=windows.reduce((max,item)=>Math.max(max,item.percentage),0);return{plan:{id:plan.id,name:plan.name},windows,nearestPercentage,blocked:windows.some(item=>item.usedTokens>=item.tokenLimit),credits:creditsFor(userId,plan.id,at)};}
export function assertPlanAccess(userId:string,modelId:string,sourceModelId?:string){const plan=userPlan(userId);if(!plan||!modelAllowedByPlan(plan.servedModelIds,modelId,sourceModelId))throw new AuthError("현재 플랜에서 사용할 수 없는 모델입니다.",403);const status=usageStatus(userId);if(status.blocked)throw new AuthError("토큰 사용 한도에 도달했습니다. 한도가 초기화되거나 리셋권을 사용한 뒤 다시 시도해 주세요.",429);}
export function acquirePlanAdmission(userId:string,modelId:string,sourceModelId?:string){db.transaction(()=>{db.prepare("DELETE FROM token_usage_admissions WHERE started_at<?").run(new Date(Date.now()-24*3600_000).toISOString());assertPlanAccess(userId,modelId,sourceModelId);try{db.prepare("INSERT INTO token_usage_admissions(user_id,started_at) VALUES(?,?)").run(userId,new Date().toISOString());}catch(error){if(String(error).includes("UNIQUE"))throw new AuthError("이 계정의 다른 응답이 진행 중입니다. 완료된 뒤 다시 시도해 주세요.",429);throw error;}})();}
/** The account's own plan weights, keyed by served model id. */
export function planModelWeights(userId:string):Record<string,number>{return userPlan(userId)?.modelWeights||{};}
export function releasePlanAdmission(userId:string){return db.prepare("DELETE FROM token_usage_admissions WHERE user_id=?").run(userId).changes>0;}
export function remainingPlanOutputTokens(userId:string,modelId:string){const plan=userPlan(userId);if(!plan)return;const weight=plan.modelWeights[modelId]||1,windows=usageStatus(userId).windows.filter(item=>item.tokenScope!=="input");if(!windows.length)return;return Math.max(0,Math.floor(Math.min(...windows.map(item=>(item.tokenLimit-item.usedTokens)/weight))));}
export function recordTokenUsage(userId:string,modelId:string,inputTokens=0,outputTokens=0){if(inputTokens<=0&&outputTokens<=0)return;db.prepare("INSERT INTO token_usage_events(user_id,model_id,input_tokens,output_tokens,created_at) VALUES(?,?,?,?,?)").run(userId,modelId,Math.max(0,Math.floor(inputTokens)),Math.max(0,Math.floor(outputTokens)),new Date().toISOString());}

const creditSchema=z.object({targetType:z.enum(["user","plan"]),targetId:z.string().min(1).optional(),targetIds:z.array(z.string().min(1)).max(10000).optional(),maxWindowSeconds:z.number().int().min(3600).max(31536000),expiresAt:z.string().min(1).max(40),title:z.string().trim().min(1).max(120)});
// A user credit may target many accounts at once; each account receives its own credit row in one transaction.
export function createResetCredit(actor:AuthUser,input:unknown){const{targetIds,targetId,...value}=creditSchema.parse(input),expiry=new Date(value.expiresAt);if(!Number.isFinite(expiry.getTime())||expiry.getTime()<=Date.now())throw new AuthError("만료일은 현재보다 이후여야 합니다.",400);const expiresAt=expiry.toISOString();const ids=[...new Set([...(targetIds||[]),...(targetId?[targetId]:[])])];if(!ids.length)throw new AuthError("리셋권 대상을 선택해 주세요.",400);if(value.targetType==="plan"&&ids.length>1)throw new AuthError("플랜 리셋권은 한 번에 하나의 플랜에만 지급할 수 있습니다.",400);const exists=db.prepare(value.targetType==="user"?"SELECT 1 FROM users WHERE id=?":"SELECT 1 FROM plans WHERE id=?");const insert=db.prepare("INSERT INTO reset_credits(id,target_type,target_id,max_window_seconds,expires_at,title,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)");const stamp=new Date().toISOString();return db.transaction(()=>ids.map(target=>{if(!exists.get(target))throw new AuthError("리셋권 대상을 찾을 수 없습니다.",404);const id=randomUUID();insert.run(id,value.targetType,target,value.maxWindowSeconds,expiresAt,value.title,stamp,actor.id);logAdminAudit(actor.id,value.targetType==="user"?target:actor.id,"reset-credit.create",JSON.stringify({...value,targetId:target,expiresAt,id}));return{id,...value,targetId:target,expiresAt};}))();}
export function redeemResetCredit(userId:string,creditId:string){const status=usageStatus(userId);const credit=status.credits.find(item=>item.id===creditId);if(!credit)throw new AuthError("사용할 수 있는 리셋권을 찾을 수 없습니다.",404);const stamp=new Date().toISOString();db.transaction(()=>{db.prepare("INSERT INTO reset_credit_redemptions(credit_id,user_id,redeemed_at) VALUES(?,?,?)").run(creditId,userId,stamp);db.prepare("INSERT INTO token_usage_resets(id,user_id,max_window_seconds,reset_at) VALUES(?,?,?,?)").run(randomUUID(),userId,credit.maxWindowSeconds,stamp);})();return usageStatus(userId);}
